# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\instance\sound.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelResref = QtWidgets.QLabel(Dialog)
        self.labelResref.setObjectName("labelResref")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelResref)
        self.resrefEdit = QtWidgets.QLineEdit(Dialog)
        self.resrefEdit.setMaxLength(16)
        self.resrefEdit.setObjectName("resrefEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.resrefEdit)
        self.labelPos = QtWidgets.QLabel(Dialog)
        self.labelPos.setObjectName("labelPos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPos)
        self.posLayout = QtWidgets.QHBoxLayout()
        self.posLayout.setObjectName("posLayout")
        self.xPosSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.xPosSpin.setMinimum(-1000000.0)
        self.xPosSpin.setMaximum(1000000.0)
        self.xPosSpin.setDecimals(4)
        self.xPosSpin.setObjectName("xPosSpin")
        self.posLayout.addWidget(self.xPosSpin)
        self.yPosSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.yPosSpin.setMinimum(-1000000.0)
        self.yPosSpin.setMaximum(1000000.0)
        self.yPosSpin.setDecimals(4)
        self.yPosSpin.setObjectName("yPosSpin")
        self.posLayout.addWidget(self.yPosSpin)
        self.zPosSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.zPosSpin.setMinimum(-1000000.0)
        self.zPosSpin.setMaximum(1000000.0)
        self.zPosSpin.setDecimals(4)
        self.zPosSpin.setObjectName("zPosSpin")
        self.posLayout.addWidget(self.zPosSpin)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.posLayout)
        self.labelTag = QtWidgets.QLabel(Dialog)
        self.labelTag.setObjectName("labelTag")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelTag)
        self.tagEdit = QtWidgets.QLineEdit(Dialog)
        self.tagEdit.setObjectName("tagEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tagEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sound Instance"))
        self.labelResref.setText(_translate("Dialog", "Template ResRef"))
        self.labelPos.setText(_translate("Dialog", "Position"))
        self.labelTag.setText(_translate("Dialog", "Tag"))
