# Form implementation generated from reading ui file '..\ui\widgets\blender_connection_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 30)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(4, 2, 4, 2)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.indicatorLabel = QtWidgets.QLabel(parent=Form)
        self.indicatorLabel.setObjectName("indicatorLabel")
        self.horizontalLayout.addWidget(self.indicatorLabel)
        self.statusLabel = QtWidgets.QLabel(parent=Form)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout.addWidget(self.statusLabel)
        self.connectButton = QtWidgets.QPushButton(parent=Form)
        self.connectButton.setMaximumHeight(22)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.indicatorLabel.setText(_translate("Form", "●"))
        self.statusLabel.setText(_translate("Form", "Disconnected"))
        self.statusLabel.setStyleSheet(_translate("Form", "font-size: 11px;"))
        self.connectButton.setText(_translate("Form", "Connect"))
