# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\command_palette.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        Dialog.setMinimumSize(QtCore.QSize(500, 0))
        Dialog.setMaximumSize(QtCore.QSize(700, 16777215))
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: palette(window);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 4px;\n"
"}\n"
"QLineEdit {\n"
"    background-color: palette(base);\n"
"    color: palette(text);\n"
"    border: none;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    border-bottom: 1px solid palette(mid);\n"
"}\n"
"QListWidget {\n"
"    background-color: palette(base);\n"
"    color: palette(text);\n"
"    border: none;\n"
"    padding: 4px;\n"
"}\n"
"QListWidget::item {\n"
"    padding: 6px 8px;\n"
"    border-radius: 2px;\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: palette(highlight);\n"
"    color: palette(highlightedText);\n"
"}\n"
"QListWidget::item:hover {\n"
"    background-color: palette(button);\n"
"}")
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.searchEdit = QtWidgets.QLineEdit(Dialog)
        self.searchEdit.setObjectName("searchEdit")
        self.mainLayout.addWidget(self.searchEdit)
        self.commandList = QtWidgets.QListWidget(Dialog)
        self.commandList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.commandList.setObjectName("commandList")
        self.mainLayout.addWidget(self.commandList)
        self.statusLabel = QtWidgets.QLabel(Dialog)
        self.statusLabel.setText("")
        self.statusLabel.setStyleSheet("padding: 4px 8px; color: palette(mid); font-size: 11px;")
        self.statusLabel.setObjectName("statusLabel")
        self.mainLayout.addWidget(self.statusLabel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Command Palette"))
        self.searchEdit.setPlaceholderText(_translate("Dialog", "Type to search commands..."))
