# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\debug_callstack_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_DebugCallStackWidget(object):
    def setupUi(self, DebugCallStackWidget):
        DebugCallStackWidget.setObjectName("DebugCallStackWidget")
        DebugCallStackWidget.resize(500, 400)
        self.mainLayout = QtWidgets.QVBoxLayout(DebugCallStackWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.table = QtWidgets.QTableWidget(DebugCallStackWidget)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.mainLayout.addWidget(self.table)

        self.retranslateUi(DebugCallStackWidget)
        QtCore.QMetaObject.connectSlotsByName(DebugCallStackWidget)

    def retranslateUi(self, DebugCallStackWidget):
        _translate = QtCore.QCoreApplication.translate
        DebugCallStackWidget.setWindowTitle(_translate("DebugCallStackWidget", "Debug Call Stack"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("DebugCallStackWidget", "Frame"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("DebugCallStackWidget", "Function"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("DebugCallStackWidget", "Instruction"))
