# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\debug_variables_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_DebugVariablesWidget(object):
    def setupUi(self, DebugVariablesWidget):
        DebugVariablesWidget.setObjectName("DebugVariablesWidget")
        DebugVariablesWidget.resize(500, 400)
        self.mainLayout = QtWidgets.QVBoxLayout(DebugVariablesWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.table = QtWidgets.QTableWidget(DebugVariablesWidget)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.mainLayout.addWidget(self.table)

        self.retranslateUi(DebugVariablesWidget)
        QtCore.QMetaObject.connectSlotsByName(DebugVariablesWidget)

    def retranslateUi(self, DebugVariablesWidget):
        _translate = QtCore.QCoreApplication.translate
        DebugVariablesWidget.setWindowTitle(_translate("DebugVariablesWidget", "Debug Variables"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("DebugVariablesWidget", "Name"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("DebugVariablesWidget", "Type"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("DebugVariablesWidget", "Value"))
