# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\debug_watch_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_DebugWatchWidget(object):
    def setupUi(self, DebugWatchWidget):
        DebugWatchWidget.setObjectName("DebugWatchWidget")
        DebugWatchWidget.resize(500, 400)
        self.mainLayout = QtWidgets.QVBoxLayout(DebugWatchWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.inputLayout = QtWidgets.QVBoxLayout()
        self.inputLayout.setContentsMargins(4, 4, 4, 4)
        self.inputLayout.setSpacing(4)
        self.inputLayout.setObjectName("inputLayout")
        self.expressionInput = QtWidgets.QLineEdit(DebugWatchWidget)
        self.expressionInput.setObjectName("expressionInput")
        self.inputLayout.addWidget(self.expressionInput)
        self.addButton = QtWidgets.QPushButton(DebugWatchWidget)
        self.addButton.setObjectName("addButton")
        self.inputLayout.addWidget(self.addButton)
        self.mainLayout.addLayout(self.inputLayout)
        self.table = QtWidgets.QTableWidget(DebugWatchWidget)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.mainLayout.addWidget(self.table)

        self.retranslateUi(DebugWatchWidget)
        QtCore.QMetaObject.connectSlotsByName(DebugWatchWidget)

    def retranslateUi(self, DebugWatchWidget):
        _translate = QtCore.QCoreApplication.translate
        DebugWatchWidget.setWindowTitle(_translate("DebugWatchWidget", "Watch Expressions"))
        self.expressionInput.setPlaceholderText(_translate("DebugWatchWidget", "Enter expression to watch..."))
        self.addButton.setText(_translate("DebugWatchWidget", "Add Watch"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("DebugWatchWidget", "Expression"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("DebugWatchWidget", "Value"))
