# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\find_replace_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_FindReplaceWidget(object):
    def setupUi(self, FindReplaceWidget):
        FindReplaceWidget.setObjectName("FindReplaceWidget")
        FindReplaceWidget.resize(800, 40)
        self.mainLayout = QtWidgets.QHBoxLayout(FindReplaceWidget)
        self.mainLayout.setContentsMargins(8, 4, 8, 4)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.findLabel = QtWidgets.QLabel(FindReplaceWidget)
        self.findLabel.setObjectName("findLabel")
        self.mainLayout.addWidget(self.findLabel)
        self.findInput = QtWidgets.QLineEdit(FindReplaceWidget)
        self.findInput.setMinimumSize(QtCore.QSize(200, 0))
        self.findInput.setObjectName("findInput")
        self.mainLayout.addWidget(self.findInput)
        self.prevButton = QtWidgets.QPushButton(FindReplaceWidget)
        self.prevButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.prevButton.setObjectName("prevButton")
        self.mainLayout.addWidget(self.prevButton)
        self.nextButton = QtWidgets.QPushButton(FindReplaceWidget)
        self.nextButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.nextButton.setObjectName("nextButton")
        self.mainLayout.addWidget(self.nextButton)
        self.replaceLabel = QtWidgets.QLabel(FindReplaceWidget)
        self.replaceLabel.setObjectName("replaceLabel")
        self.mainLayout.addWidget(self.replaceLabel)
        self.replaceInput = QtWidgets.QLineEdit(FindReplaceWidget)
        self.replaceInput.setMinimumSize(QtCore.QSize(200, 0))
        self.replaceInput.setObjectName("replaceInput")
        self.mainLayout.addWidget(self.replaceInput)
        self.replaceButton = QtWidgets.QPushButton(FindReplaceWidget)
        self.replaceButton.setObjectName("replaceButton")
        self.mainLayout.addWidget(self.replaceButton)
        self.replaceAllButton = QtWidgets.QPushButton(FindReplaceWidget)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.mainLayout.addWidget(self.replaceAllButton)
        self.caseSensitiveCheck = QtWidgets.QCheckBox(FindReplaceWidget)
        self.caseSensitiveCheck.setObjectName("caseSensitiveCheck")
        self.mainLayout.addWidget(self.caseSensitiveCheck)
        self.wholeWordsCheck = QtWidgets.QCheckBox(FindReplaceWidget)
        self.wholeWordsCheck.setObjectName("wholeWordsCheck")
        self.mainLayout.addWidget(self.wholeWordsCheck)
        self.regexCheck = QtWidgets.QCheckBox(FindReplaceWidget)
        self.regexCheck.setObjectName("regexCheck")
        self.mainLayout.addWidget(self.regexCheck)
        self.closeButton = QtWidgets.QPushButton(FindReplaceWidget)
        self.closeButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.closeButton.setObjectName("closeButton")
        self.mainLayout.addWidget(self.closeButton)

        self.retranslateUi(FindReplaceWidget)
        QtCore.QMetaObject.connectSlotsByName(FindReplaceWidget)

    def retranslateUi(self, FindReplaceWidget):
        _translate = QtCore.QCoreApplication.translate
        FindReplaceWidget.setWindowTitle(_translate("FindReplaceWidget", "Find/Replace"))
        self.findLabel.setText(_translate("FindReplaceWidget", "Find:"))
        self.findInput.setPlaceholderText(_translate("FindReplaceWidget", "Find..."))
        self.prevButton.setText(_translate("FindReplaceWidget", "↑"))
        self.prevButton.setToolTip(_translate("FindReplaceWidget", "Find Previous (Shift+F3)"))
        self.nextButton.setText(_translate("FindReplaceWidget", "↓"))
        self.nextButton.setToolTip(_translate("FindReplaceWidget", "Find Next (F3)"))
        self.replaceLabel.setText(_translate("FindReplaceWidget", "Replace:"))
        self.replaceInput.setPlaceholderText(_translate("FindReplaceWidget", "Replace..."))
        self.replaceButton.setText(_translate("FindReplaceWidget", "Replace"))
        self.replaceAllButton.setText(_translate("FindReplaceWidget", "Replace All"))
        self.caseSensitiveCheck.setText(_translate("FindReplaceWidget", "Aa"))
        self.caseSensitiveCheck.setToolTip(_translate("FindReplaceWidget", "Match Case"))
        self.wholeWordsCheck.setText(_translate("FindReplaceWidget", "Ab"))
        self.wholeWordsCheck.setToolTip(_translate("FindReplaceWidget", "Match Whole Word"))
        self.regexCheck.setText(_translate("FindReplaceWidget", ".*"))
        self.regexCheck.setToolTip(_translate("FindReplaceWidget", "Use Regular Expression"))
        self.closeButton.setText(_translate("FindReplaceWidget", "✕"))
        self.closeButton.setToolTip(_translate("FindReplaceWidget", "Close (Escape)"))
