# Form implementation generated from reading ui file '..\ui\widgets\find_bar.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 30)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.findInput = QtWidgets.QLineEdit(parent=Widget)
        self.findInput.setObjectName("findInput")
        self.horizontalLayout.addWidget(self.findInput)
        self.backButton = QtWidgets.QPushButton(parent=Widget)
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.findButton = QtWidgets.QPushButton(parent=Widget)
        self.findButton.setText("")
        self.findButton.setObjectName("findButton")
        self.horizontalLayout.addWidget(self.findButton)
        self.resultsLabel = QtWidgets.QLabel(parent=Widget)
        self.resultsLabel.setText("")
        self.resultsLabel.setObjectName("resultsLabel")
        self.horizontalLayout.addWidget(self.resultsLabel)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Form"))
