# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\go_to_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 30)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.goToInput = QtWidgets.QLineEdit(Widget)
        self.goToInput.setObjectName("goToInput")
        self.horizontalLayout.addWidget(self.goToInput)
        self.goToButton = QtWidgets.QPushButton(Widget)
        self.goToButton.setObjectName("goToButton")
        self.horizontalLayout.addWidget(self.goToButton)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Form"))
        self.goToButton.setText(_translate("Widget", "Go"))
