# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\installation_toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 120)
        self.rootLayout = QtWidgets.QVBoxLayout(Form)
        self.rootLayout.setContentsMargins(8, 6, 8, 6)
        self.rootLayout.setSpacing(6)
        self.rootLayout.setObjectName("rootLayout")
        self.topRow = QtWidgets.QHBoxLayout()
        self.topRow.setObjectName("topRow")
        self.installationLabel = QtWidgets.QLabel(Form)
        self.installationLabel.setObjectName("installationLabel")
        self.topRow.addWidget(self.installationLabel)
        self.installationCombo = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installationCombo.sizePolicy().hasHeightForWidth())
        self.installationCombo.setSizePolicy(sizePolicy)
        self.installationCombo.setObjectName("installationCombo")
        self.topRow.addWidget(self.installationCombo)
        self.reloadBtn = QtWidgets.QPushButton(Form)
        self.reloadBtn.setObjectName("reloadBtn")
        self.topRow.addWidget(self.reloadBtn)
        self.manageBtn = QtWidgets.QPushButton(Form)
        self.manageBtn.setObjectName("manageBtn")
        self.topRow.addWidget(self.manageBtn)
        self.rootLayout.addLayout(self.topRow)
        self.modeRow = QtWidgets.QHBoxLayout()
        self.modeRow.setObjectName("modeRow")
        self.modeFullRadio = QtWidgets.QRadioButton(Form)
        self.modeFullRadio.setChecked(True)
        self.modeFullRadio.setObjectName("modeFullRadio")
        self.modeRow.addWidget(self.modeFullRadio)
        self.modeFolderRadio = QtWidgets.QRadioButton(Form)
        self.modeFolderRadio.setObjectName("modeFolderRadio")
        self.modeRow.addWidget(self.modeFolderRadio)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.modeRow.addItem(spacerItem)
        self.rootLayout.addLayout(self.modeRow)
        self.pathsWidget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathsWidget.sizePolicy().hasHeightForWidth())
        self.pathsWidget.setSizePolicy(sizePolicy)
        self.pathsWidget.setObjectName("pathsWidget")
        self.pathsLayout = QtWidgets.QFormLayout(self.pathsWidget)
        self.pathsLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.pathsLayout.setContentsMargins(0, 0, 0, 0)
        self.pathsLayout.setObjectName("pathsLayout")
        self.rootLayout.addWidget(self.pathsWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.installationLabel.setText(_translate("Form", "Installation:"))
        self.reloadBtn.setText(_translate("Form", "Reload"))
        self.manageBtn.setText(_translate("Form", "Manage..."))
        self.modeFullRadio.setText(_translate("Form", "Full installation"))
        self.modeFolderRadio.setText(_translate("Form", "Specify folder paths"))
