# Form implementation generated from reading ui file '..\ui\widgets\left_dock_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(200, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.orphanedNodesLabel = QtWidgets.QLabel(parent=Widget)
        self.orphanedNodesLabel.setObjectName("orphanedNodesLabel")
        self.verticalLayout.addWidget(self.orphanedNodesLabel)
        self.orphanedNodesList = QtWidgets.QListWidget(parent=Widget)
        self.orphanedNodesList.setObjectName("orphanedNodesList")
        self.verticalLayout.addWidget(self.orphanedNodesList)
        self.pinnedItemsLabel = QtWidgets.QLabel(parent=Widget)
        self.pinnedItemsLabel.setObjectName("pinnedItemsLabel")
        self.verticalLayout.addWidget(self.pinnedItemsLabel)
        self.pinnedItemsList = QtWidgets.QListWidget(parent=Widget)
        self.pinnedItemsList.setObjectName("pinnedItemsList")
        self.verticalLayout.addWidget(self.pinnedItemsList)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Form"))
        self.orphanedNodesLabel.setText(_translate("Widget", "Orphaned Nodes"))
        self.pinnedItemsLabel.setText(_translate("Widget", "Pinned Items"))
