# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\lyt_editor_controls.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar = QtWidgets.QToolBar(Form)
        self.toolbar.setObjectName("toolbar")
        self.verticalLayout.addWidget(self.toolbar)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addRoomButton = QtWidgets.QPushButton(Form)
        self.addRoomButton.setObjectName("addRoomButton")
        self.buttonLayout.addWidget(self.addRoomButton)
        self.addTrackButton = QtWidgets.QPushButton(Form)
        self.addTrackButton.setObjectName("addTrackButton")
        self.buttonLayout.addWidget(self.addTrackButton)
        self.addObstacleButton = QtWidgets.QPushButton(Form)
        self.addObstacleButton.setObjectName("addObstacleButton")
        self.buttonLayout.addWidget(self.addObstacleButton)
        self.addDoorhookButton = QtWidgets.QPushButton(Form)
        self.addDoorhookButton.setObjectName("addDoorhookButton")
        self.buttonLayout.addWidget(self.addDoorhookButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.zoomLayout = QtWidgets.QHBoxLayout()
        self.zoomLayout.setObjectName("zoomLayout")
        self.zoomLabel = QtWidgets.QLabel(Form)
        self.zoomLabel.setObjectName("zoomLabel")
        self.zoomLayout.addWidget(self.zoomLabel)
        self.zoomSlider = QtWidgets.QSlider(Form)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setMinimum(10)
        self.zoomSlider.setMaximum(200)
        self.zoomSlider.setProperty("value", 100)
        self.zoomSlider.setObjectName("zoomSlider")
        self.zoomLayout.addWidget(self.zoomSlider)
        self.verticalLayout.addLayout(self.zoomLayout)
        self.textureList = QtWidgets.QListWidget(Form)
        self.textureList.setObjectName("textureList")
        self.verticalLayout.addWidget(self.textureList)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addRoomButton.setText(_translate("Form", "Add Room"))
        self.addTrackButton.setText(_translate("Form", "Add Track"))
        self.addObstacleButton.setText(_translate("Form", "Add Obstacle"))
        self.addDoorhookButton.setText(_translate("Form", "Add Door Hook"))
        self.zoomLabel.setText(_translate("Form", "Zoom:"))
