# Form implementation generated from reading ui file '..\ui\widgets\lyt_editor_panel.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridControlsLayout = QtWidgets.QHBoxLayout()
        self.gridControlsLayout.setObjectName("gridControlsLayout")
        self.showGridCheckbox = QtWidgets.QCheckBox(parent=Form)
        self.showGridCheckbox.setObjectName("showGridCheckbox")
        self.gridControlsLayout.addWidget(self.showGridCheckbox)
        self.snapGridCheckbox = QtWidgets.QCheckBox(parent=Form)
        self.snapGridCheckbox.setObjectName("snapGridCheckbox")
        self.gridControlsLayout.addWidget(self.snapGridCheckbox)
        self.gridSizeLabel = QtWidgets.QLabel(parent=Form)
        self.gridSizeLabel.setObjectName("gridSizeLabel")
        self.gridControlsLayout.addWidget(self.gridSizeLabel)
        self.gridSizeSpinBox = QtWidgets.QSpinBox(parent=Form)
        self.gridSizeSpinBox.setMinimum(10)
        self.gridSizeSpinBox.setMaximum(1000)
        self.gridSizeSpinBox.setObjectName("gridSizeSpinBox")
        self.gridControlsLayout.addWidget(self.gridSizeSpinBox)
        self.verticalLayout.addLayout(self.gridControlsLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.addRoomButton = QtWidgets.QPushButton(parent=Form)
        self.addRoomButton.setObjectName("addRoomButton")
        self.buttonLayout.addWidget(self.addRoomButton)
        self.addTrackButton = QtWidgets.QPushButton(parent=Form)
        self.addTrackButton.setObjectName("addTrackButton")
        self.buttonLayout.addWidget(self.addTrackButton)
        self.addObstacleButton = QtWidgets.QPushButton(parent=Form)
        self.addObstacleButton.setObjectName("addObstacleButton")
        self.buttonLayout.addWidget(self.addObstacleButton)
        self.placeDoorHookButton = QtWidgets.QPushButton(parent=Form)
        self.placeDoorHookButton.setObjectName("placeDoorHookButton")
        self.buttonLayout.addWidget(self.placeDoorHookButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.zoomLayout = QtWidgets.QHBoxLayout()
        self.zoomLayout.setObjectName("zoomLayout")
        self.zoomLabel = QtWidgets.QLabel(parent=Form)
        self.zoomLabel.setObjectName("zoomLabel")
        self.zoomLayout.addWidget(self.zoomLabel)
        self.zoomSlider = QtWidgets.QSlider(parent=Form)
        self.zoomSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.zoomSlider.setMinimum(10)
        self.zoomSlider.setMaximum(200)
        self.zoomSlider.setProperty("value", 100)
        self.zoomSlider.setObjectName("zoomSlider")
        self.zoomLayout.addWidget(self.zoomSlider)
        self.verticalLayout.addLayout(self.zoomLayout)
        self.textureList = QtWidgets.QListWidget(parent=Form)
        self.textureList.setObjectName("textureList")
        self.verticalLayout.addWidget(self.textureList)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.showGridCheckbox.setText(_translate("Form", "Show Grid"))
        self.snapGridCheckbox.setText(_translate("Form", "Snap to Grid"))
        self.gridSizeLabel.setText(_translate("Form", "Grid Size:"))
        self.addRoomButton.setText(_translate("Form", "Add Room"))
        self.addTrackButton.setText(_translate("Form", "Add Track"))
        self.addObstacleButton.setText(_translate("Form", "Add Obstacle"))
        self.placeDoorHookButton.setText(_translate("Form", "Place Door Hook"))
        self.zoomLabel.setText(_translate("Form", "Zoom:"))
