# Form implementation generated from reading ui file '..\ui\widgets\media_player_controls.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 30)
        self.buttonLayout = QtWidgets.QHBoxLayout(Form)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setSpacing(0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.playPauseButton = QtWidgets.QPushButton(parent=Form)
        self.playPauseButton.setFixedSize(QtCore.QSize(24, 24))
        self.playPauseButton.setObjectName("playPauseButton")
        self.buttonLayout.addWidget(self.playPauseButton)
        self.stopButton = QtWidgets.QPushButton(parent=Form)
        self.stopButton.setFixedSize(QtCore.QSize(24, 24))
        self.stopButton.setObjectName("stopButton")
        self.buttonLayout.addWidget(self.stopButton)
        self.muteButton = QtWidgets.QPushButton(parent=Form)
        self.muteButton.setFixedSize(QtCore.QSize(24, 24))
        self.muteButton.setObjectName("muteButton")
        self.buttonLayout.addWidget(self.muteButton)
        self.timeLabel = QtWidgets.QLabel(parent=Form)
        self.timeLabel.setObjectName("timeLabel")
        self.buttonLayout.addWidget(self.timeLabel)
        self.timeSlider = QtWidgets.QSlider(parent=Form)
        self.timeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.timeSlider.setMouseTracking(True)
        self.timeSlider.setObjectName("timeSlider")
        self.buttonLayout.addWidget(self.timeSlider)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.timeLabel.setText(_translate("Form", "00:00 / 00:00"))
