# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\resource_filesystem_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.mainLayout = QtWidgets.QVBoxLayout(Form)
        self.mainLayout.setObjectName("mainLayout")
        self.addressLayout = QtWidgets.QHBoxLayout()
        self.addressLayout.setObjectName("addressLayout")
        self.addressBar = QtWidgets.QLineEdit(Form)
        self.addressBar.setObjectName("addressBar")
        self.addressLayout.addWidget(self.addressBar)
        self.goButton = QtWidgets.QPushButton(Form)
        self.goButton.setObjectName("goButton")
        self.addressLayout.addWidget(self.goButton)
        self.refreshButton = QtWidgets.QPushButton(Form)
        self.refreshButton.setObjectName("refreshButton")
        self.addressLayout.addWidget(self.refreshButton)
        self.mainLayout.addLayout(self.addressLayout)
        self.fsTreeView = QtWidgets.QTreeView(Form)
        self.fsTreeView.setHeaderHidden(False)
        self.fsTreeView.setObjectName("fsTreeView")
        self.mainLayout.addWidget(self.fsTreeView)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.goButton.setText(_translate("Form", "Go"))
        self.refreshButton.setText(_translate("Form", "Refresh"))
