# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\terminal_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(600, 400)
        self.mainLayout = QtWidgets.QVBoxLayout(Widget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.terminalOutput = QtWidgets.QPlainTextEdit(Widget)
        self.terminalOutput.setReadOnly(True)
        self.terminalOutput.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.terminalOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.terminalOutput.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.terminalOutput.setStyleSheet("QPlainTextEdit {\n"
"       background-color: palette(base);\n"
"       color: palette(text);\n"
"       border: none;\n"
"       padding: 8px;\n"
"       selection-background-color: palette(highlight);\n"
"       selection-color: palette(highlighted-text);\n"
"       }\n"
"       QScrollBar:vertical {\n"
"       background-color: palette(base);\n"
"       width: 14px;\n"
"       border: none;\n"
"       }\n"
"       QScrollBar::handle:vertical {\n"
"       background-color: palette(mid);\n"
"       min-height: 30px;\n"
"       border-radius: 7px;\n"
"       }\n"
"       QScrollBar::handle:vertical:hover {\n"
"       background-color: palette(dark);\n"
"       }\n"
"       QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"       height: 0px;\n"
"       }")
        self.terminalOutput.setObjectName("terminalOutput")
        self.mainLayout.addWidget(self.terminalOutput)
        self.terminalInput = QtWidgets.QLineEdit(Widget)
        self.terminalInput.setStyleSheet("QLineEdit {\n"
"       background-color: palette(base);\n"
"       color: palette(text);\n"
"       border: none;\n"
"       padding: 6px 8px;\n"
"       selection-background-color: palette(highlight);\n"
"       selection-color: palette(highlighted-text);\n"
"       }")
        self.terminalInput.setObjectName("terminalInput")
        self.mainLayout.addWidget(self.terminalInput)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        pass
