# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\texture_browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 300)
        self.mainLayout = QtWidgets.QVBoxLayout(Widget)
        self.mainLayout.setContentsMargins(9, 9, 9, 9)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.importButton = QtWidgets.QPushButton(Widget)
        self.importButton.setObjectName("importButton")
        self.mainLayout.addWidget(self.importButton)
        self.scrollArea = QtWidgets.QScrollArea(Widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 382, 266))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textureLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.textureLayout.setSpacing(6)
        self.textureLayout.setObjectName("textureLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainLayout.addWidget(self.scrollArea)
        self.textureList = QtWidgets.QListWidget(Widget)
        self.textureList.setViewMode(QtWidgets.QListWidget.IconMode)
        self.textureList.setIconSize(QtCore.QSize(64, 64))
        self.textureList.setResizeMode(QtWidgets.QListWidget.Adjust)
        self.textureList.setObjectName("textureList")
        self.mainLayout.addWidget(self.textureList)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        self.importButton.setText(_translate("Widget", "Import Texture"))
