#!/usr/bin/env python3
"""Regenerate workspace config from the current Tools/* layout."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tool_metadata import (  # noqa: E402
    LIBRARY_SOURCE_PATHS,
    LIBRARY_TEST_PATHS,
    discover_tools,
)

WINDOWS_PATH_SEPARATOR = ";"
ROOT_GIT_TOOL_SOURCES = {
    "holocrontoolset": "HolocronToolset",
    "holopatcher": "HoloPatcher",
    "holopazaak": "HoloPazaak",
    "kotordiff": "KotorDiff",
}


def _write_text(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _replace_section(text: str, start_header: str, end_header: str, replacement: str) -> str:
    pattern = re.compile(rf"(?ms)^\{start_header}\n.*?(?=^\{end_header})")
    new_text, count = pattern.subn(replacement.rstrip() + "\n\n", text, count=1)
    if count != 1:
        raise RuntimeError(f"Failed to replace section {start_header} -> {end_header}")
    return new_text


def _render_path_list(paths: list[str], indent: str = "  ") -> str:
    return "[\n" + "\n".join(f'{indent}"{path}",' for path in paths) + "\n]"


def sync_pyproject() -> None:
    tools = discover_tools(REPO_ROOT)
    tool_src_paths = [tool.src_path for tool in tools]
    tool_test_paths = [tool.tests_path for tool in tools if tool.tests_path]

    pyproject_path = REPO_ROOT / "pyproject.toml"
    text = pyproject_path.read_text(encoding="utf-8")

    uv_sources = "\n".join(
        [
            "[tool.uv.sources]",
            "# Generated by helper_scripts/sync_tooling.py",
            "# Keep root uv sources Git-safe: resolve sibling tools from their Git repos, not submodules.",
            *(
                f'{project_name} = {{ git = "https://github.com/OpenKotOR/{repo_name}" }}'
                for project_name, repo_name in ROOT_GIT_TOOL_SOURCES.items()
            ),
            "pykotorcli = { workspace = true }",
            "pykotor = { workspace = true }",
            "bioware-kaitai-formats = { workspace = true }",
        ]
    )
    workspace_block = "\n".join(
        [
            "[tool.uv.workspace]",
            "members = [",
            '  "Libraries/PyKotor",',
            '  "Libraries/bioware-kaitai-formats",',
            "]",
        ]
    )
    mypy_block = "\n".join(
        [
            "[tool.mypy]",
            "check_untyped_defs = true",
            "disallow_untyped_defs = false",
            "exclude = [",
                "  '\\.mypy_cache',",
                "  '\\.venv',",
            '  "__pycache__",',
            '  "build",',
            '  "dist",',
            '  "tests/results",',
            '  "venv"',
            "]",
            "explicit_package_bases = true",
            f"mypy_path = {_render_path_list(LIBRARY_SOURCE_PATHS + tool_src_paths + ['tests'])}",
            "namespace_packages = true",
            "no_implicit_optional = true",
            'python_version = "3.9"  # must be set to the minimum supported python version',
            "warn_return_any = true",
            "warn_unused_configs = true",
        ]
    )
    pyright_block = "\n".join(
        [
            "[tool.pyright]",
            "analyzeUnannotatedFunctions = true",
            "deprecateTypingAliases = false",
            "exclude = [",
            '  "**/.*/**",',
            '  "**/.venv/**",',
            '  "**/__pycache__/**",',
            '  "**/build/**",',
            '  "**/dist/**",',
            '  "**/node_modules/**",',
            '  "**/vendor/**",',
            '  "**/venv/**"',
            "]",
            f"extraPaths = {_render_path_list(LIBRARY_SOURCE_PATHS + tool_src_paths)}",
            'include = ["*.py"]',
            'pythonVersion = "3.8"',
            "reportMissingImports = true",
            "reportMissingTypeStubs = false",
            'typeCheckingMode = "basic"',
        ]
    )
    pytest_block = "\n".join(
        [
            "[tool.pytest.ini_options]",
            "addopts = '-ra -q -m \"not slow\"'",
            "log_cli = true",
            'log_cli_format = "%(message)s"',
            'log_cli_level = "CRITICAL"',
            'log_file = "pytest.log"',
            'log_file_date_format = "%Y-%m-%d %H:%M:%S"',
            'log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"',
            'log_file_level = "DEBUG"',
            "markers = [",
            '  "gui: marks tests that require a GUI (deselect with \'-m \\"not gui\\"\')",',
            '  "slow: marks tests that are slow (deselect with \'-m \\"not slow\\"\')"',
            "]",
            'qt_api = "pyqt6" # Default, can be overridden by PYTEST_QT_API environment variable (moved to conftest.py)',
            f"testpaths = {_render_path_list(LIBRARY_TEST_PATHS + tool_test_paths + ['tests'])}",
            "timeout = 120 # 2 minutes per test",
            'timeout_method = "thread" # Use thread-based timeout (works on Windows)',
        ]
    )
    ruff_block = "\n".join(
        [
            "[tool.ruff]",
            "fix = true",
            "force-exclude = true",
            "line-length = 100",
            'output-format = "grouped" # Group violations by containing file.',
            "preview = false",
            "respect-gitignore = false",
            "show-fixes = true",
            f"src = {_render_path_list(['Libraries/PyKotor/src'] + tool_src_paths)}",
        ]
    )

    text = _replace_section(text, "[tool.uv.sources]", "[tool.uv.workspace]", uv_sources)
    text = _replace_section(
        text,
        "[tool.uv.workspace]",
        "########################################################",
        workspace_block,
    )
    text = _replace_section(text, "[tool.mypy]", "[tool.pylintrc]", mypy_block)
    text = _replace_section(text, "[tool.pyright]", "[tool.pyright.defineConstant]", pyright_block)
    text = _replace_section(text, "[tool.pytest.ini_options]", "[tool.ruff]", pytest_block)
    text = _replace_section(text, "[tool.ruff]", "[tool.ruff.format]", ruff_block)

    _write_text(pyproject_path, text)


def sync_env() -> None:
    tools = discover_tools(REPO_ROOT)
    tool_test_paths = [tool.tests_path for tool in tools if tool.tests_path]
    tool_src_paths = [tool.src_path for tool in tools]
    python_paths = LIBRARY_SOURCE_PATHS + LIBRARY_TEST_PATHS + tool_src_paths + tool_test_paths
    joined_paths = WINDOWS_PATH_SEPARATOR.join(f"./{path}" for path in python_paths)
    env_text = "\n".join(
        [
            f'MYPYPATH="{joined_paths}"',
            f'PYTHONPATH="{joined_paths}"',
            'K1_PATH="G:/SteamLibrary/steamapps/common/swkotor"',
            'K2_PATH="G:/SteamLibrary/steamapps/common/Knights of the Old Republic II"',
        ]
    )
    _write_text(REPO_ROOT / ".env", env_text)


def sync_vscode_settings() -> None:
    tools = discover_tools(REPO_ROOT)
    extra_paths = [
        f"${{workspaceFolder}}/{path}"
        for path in LIBRARY_SOURCE_PATHS + [tool.src_path for tool in tools]
    ]
    pytest_args = (
        LIBRARY_TEST_PATHS + [tool.tests_path for tool in tools if tool.tests_path] + ["-v"]
    )
    settings = {
        "[json]": {"editor.tabSize": 2},
        "[jsonc]": {"editor.tabSize": 2},
        "[xml.ui]": {"editor.insertSpaces": True, "editor.tabSize": 1},
        "[xml]": {"editor.tabSize": 2},
        "chat.mcp.discovery.enabled": {"cursor-workspace": True},
        "cmake.ignoreCMakeListsMissing": True,
        "cursorpyright.analysis.autoImportCompletions": True,
        "cursorpyright.analysis.extraPaths": extra_paths,
        "cursorpyright.analysis.typeCheckingMode": "basic",
        "dotnet.defaultSolution": "disable",
        "editor.inlineSuggest.enabled": True,
        "editor.quickSuggestions": {"comments": True, "other": "inline", "strings": True},
        "editor.quickSuggestionsDelay": 100,
        "files.associations": {"*.ui": "xml"},
        "files.exclude": {"**/.history/**": True},
        "files.watcherExclude": {"**/.history/**": True},
        "github-actions.workflows.pinned.workflows": [".github/workflows/publish_pykotor.yml"],
        "launch": {"compounds": [], "debugStdLib": True, "justMyCode": True},
        "mypy-type-checker.args": [
            "--exclude=./.venv",
            "--exclude=tests/results",
            "--check-untyped-defs",
            "-v",
            "--disable-error-code=import-untyped",
            "--disable-error-code=no-any-return",
            "--explicit-package-bases",
            "--follow-imports=skip",
        ],
        "mypy-type-checker.importStrategy": "fromEnvironment",
        "mypy-type-checker.preferDaemon": True,
        "mypy.extraArguments": [
            "--exclude=./.venv",
            "--exclude=tests/results",
            "--check-untyped-defs",
            "-v",
            "--disable-error-code=import-untyped",
            "--disable-error-code=no-any-return",
            "--explicit-package-bases",
            "--follow-imports=skip",
        ],
        "mypy.runUsingActiveInterpreter": True,
        "pylint.enabled": False,
        "python-envs.defaultEnvManager": "ms-python.python:system",
        "python-envs.pythonProjects": [],
        "python.analysis.autoImportCompletions": True,
        "python.analysis.enablePytestSupport": True,
        "python.analysis.extraPaths": extra_paths,
        "python.analysis.findRefsInBackgroundThread": True,
        "python.analysis.typeCheckingMode": "basic",
        "python.analysis.typeEvaluation.deprecateTypingAliases": False,
        "python.analysis.typeEvaluation.strictListInference": True,
        "python.analysis.typeEvaluation.strictSetInference": True,
        "python.autoComplete.extraPaths": extra_paths,
        "python.envFile": "${workspaceFolder}/.env",
        "python.defaultInterpreterPath": "${workspaceFolder}\\.venv\\Scripts\\python.exe",
        "python.languageServer": "Default",
        "python.locator": "js",
        "python.useEnvironmentsExtension": False,
        "python.linting.enabled": True,
        "python.linting.pylintEnabled": False,
        "python.testing.pytestArgs": pytest_args,
        "python.testing.pytestEnabled": True,
        "pythonTestExplorer.outputs.showOutputsOnRun": True,
        "pythonTestExplorer.testFramework": "pytest",
        "qtForPython.rcc.liveExecution.enabled": False,
        "qtForPython.uic.liveExecution.enabled": False,
        "remote.WSL.fileWatcher.polling": True,
        "search.exclude": {"**/.history/**": True},
        "terminal.integrated.automationProfile.windows": {
            "args": ["-NoProfile", "-NoLogo"],
            "path": "pwsh.exe",
        },
    }
    _write_text(REPO_ROOT / ".vscode" / "settings.json", json.dumps(settings, indent=2))


def sync_vscode_launch() -> None:
    tools = discover_tools(REPO_ROOT)
    configurations: list[dict[str, object]] = [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (current file)",
            "cwd": "${workspaceFolder}",
            "program": "${file}",
            "args": [],
        },
        {
            "name": "PowerShell Launch Current File",
            "type": "PowerShell",
            "request": "launch",
            "script": "${file}",
            "cwd": "${fileDirname}",
        },
        {
            "name": "Python C++ Debug",
            "type": "pythoncpp",
            "request": "launch",
            "pythonConfig": "default",
            "cppConfig": "default (win) Attach",
        },
        {
            "name": "Python: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": True,
            "env": {
                "K1_PATH": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\swkotor",
                "K2_PATH": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Knights of the Old Republic II",
            },
            "pythonArgs": ["-Xfrozen_modules=off", "-Xdev"],
            "autoReload": {"enable": True},
        },
    ]
    extra_pythonpath = ";".join(
        ["${workspaceFolder}", "${workspaceFolder}/Libraries/PyKotor/src", "${env:PYTHONPATH}"]
    )
    for tool in tools:
        configurations.append(
            {
                "name": f"Run {tool.directory}",
                "type": "debugpy",
                "request": "launch",
                "module": tool.module_name,
                "cwd": f"${{workspaceFolder}}/{tool.src_path}/",
                "console": "integratedTerminal",
                "env": {
                    "PYTHONPATH": extra_pythonpath,
                    "K1_PATH": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\swkotor",
                    "K2_PATH": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Knights of the Old Republic II",
                },
                "pythonArgs": ["-Xfrozen_modules=off", "-Xdev"],
                "justMyCode": not tool.requires_qt,
                "autoReload": {"enable": True},
            }
        )
    launch = {
        "version": "0.2.0",
        "configurations": configurations,
    }
    _write_text(REPO_ROOT / ".vscode" / "launch.json", json.dumps(launch, indent=2))


def sync_vscode_tasks() -> None:
    tools = discover_tools(REPO_ROOT)
    tool_options = [tool.relative_path for tool in tools]
    tasks = {
        "version": "2.0.0",
        "inputs": [
            {
                "id": "toolPath",
                "type": "pickString",
                "description": "Select a tool under Tools/",
                "options": tool_options,
                "default": tool_options[0] if tool_options else "Tools/HoloPatcher",
            }
        ],
        "tasks": [
            {
                "label": "Install Workspace Dev Requirements",
                "type": "shell",
                "command": "${command:python.interpreterPath}",
                "args": [
                    "-m",
                    "pip",
                    "install",
                    "-r",
                    "${workspaceFolder}${pathSeparator}requirements-dev.txt",
                    "--progress-bar=on",
                    "--prefer-binary",
                    "--compile",
                    "-U",
                    "--upgrade-strategy=eager",
                ],
                "problemMatcher": [],
            },
            {
                "label": "Install PyInstaller",
                "type": "shell",
                "command": "${command:python.interpreterPath}",
                "args": ["-m", "pip", "install", "pyinstaller"],
                "problemMatcher": [],
            },
            {
                "label": "Install Tool Requirements",
                "type": "shell",
                "command": "pwsh",
                "args": [
                    "-NoProfile",
                    "-File",
                    "${workspaceFolder}${pathSeparator}compile${pathSeparator}deps_tool.ps1",
                    "--tool",
                    "${input:toolPath}",
                ],
                "problemMatcher": [],
            },
            {
                "label": "Build Tool",
                "type": "shell",
                "command": "pwsh",
                "args": [
                    "-NoProfile",
                    "-File",
                    "${workspaceFolder}${pathSeparator}compile${pathSeparator}compile_tool.ps1",
                    "--tool",
                    "${input:toolPath}",
                ],
                "group": {"kind": "build", "isDefault": False},
                "problemMatcher": [],
            },
            {
                "label": "Sync Tooling Config",
                "type": "shell",
                "command": "${command:python.interpreterPath}",
                "args": ["helper_scripts${pathSeparator}sync_tooling.py"],
                "problemMatcher": [],
            },
            {
                "label": "Python: Ruff check entire project",
                "type": "shell",
                "command": "uv",
                "args": ["run", "ruff", "check", "."],
                "problemMatcher": ["$eslint-stylish"],
            },
        ],
    }
    _write_text(REPO_ROOT / ".vscode" / "tasks.json", json.dumps(tasks, indent=2))


def main() -> None:
    sync_pyproject()
    sync_env()
    sync_vscode_settings()
    sync_vscode_launch()
    sync_vscode_tasks()
    print("Synced pyproject.toml, .env, and .vscode config from discovered tools.")


if __name__ == "__main__":
    main()
