# Form implementation generated from reading ui file '..\ui\editors\fac.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.factionLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.factionLabel.setObjectName("factionLabel")
        self.verticalLayout.addWidget(self.factionLabel)
        self.factionTree = QtWidgets.QTreeView(parent=self.centralwidget)
        self.factionTree.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.factionTree.setObjectName("factionTree")
        self.verticalLayout.addWidget(self.factionTree)
        self.reputationLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.reputationLabel.setObjectName("reputationLabel")
        self.verticalLayout.addWidget(self.reputationLabel)
        self.reputationTree = QtWidgets.QTreeView(parent=self.centralwidget)
        self.reputationTree.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.reputationTree.setObjectName("reputationTree")
        self.verticalLayout.addWidget(self.reputationTree)
        self.controlsLayout = QtWidgets.QHBoxLayout()
        self.controlsLayout.setSpacing(6)
        self.controlsLayout.setObjectName("controlsLayout")
        self.nameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameLabel.setObjectName("nameLabel")
        self.controlsLayout.addWidget(self.nameLabel)
        self.factionNameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.factionNameEdit.setObjectName("factionNameEdit")
        self.controlsLayout.addWidget(self.factionNameEdit)
        self.globalEffectCheck = QtWidgets.QPushButton(parent=self.centralwidget)
        self.globalEffectCheck.setObjectName("globalEffectCheck")
        self.controlsLayout.addWidget(self.globalEffectCheck)
        self.parentIdLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.parentIdLabel.setObjectName("parentIdLabel")
        self.controlsLayout.addWidget(self.parentIdLabel)
        self.parentIdSpin = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.parentIdSpin.setMaximum(1000)
        self.parentIdSpin.setObjectName("parentIdSpin")
        self.controlsLayout.addWidget(self.parentIdSpin)
        self.verticalLayout.addLayout(self.controlsLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.factionLabel.setText(_translate("MainWindow", "Factions:"))
        self.reputationLabel.setText(_translate("MainWindow", "Reputations:"))
        self.nameLabel.setText(_translate("MainWindow", "Name:"))
        self.globalEffectCheck.setText(_translate("MainWindow", "Toggle Global Effect"))
        self.parentIdLabel.setText(_translate("MainWindow", "Parent ID:"))
