# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\editors\view_switcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(600, 400)
        self.mainLayout = QtWidgets.QVBoxLayout(Widget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.toolbarLayout = QtWidgets.QHBoxLayout()
        self.toolbarLayout.setContentsMargins(5, 5, 5, 5)
        self.toolbarLayout.setSpacing(6)
        self.toolbarLayout.setObjectName("toolbarLayout")
        self.treeButton = QtWidgets.QPushButton(Widget)
        self.treeButton.setCheckable(True)
        self.treeButton.setChecked(True)
        self.treeButton.setObjectName("treeButton")
        self.toolbarLayout.addWidget(self.treeButton)
        self.graphButton = QtWidgets.QPushButton(Widget)
        self.graphButton.setCheckable(True)
        self.graphButton.setObjectName("graphButton")
        self.toolbarLayout.addWidget(self.graphButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbarLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.toolbarLayout)
        self.stack = QtWidgets.QStackedWidget(Widget)
        self.stack.setObjectName("stack")
        self.mainLayout.addWidget(self.stack)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        self.treeButton.setText(_translate("Widget", "Tree View"))
        self.graphButton.setText(_translate("Widget", "Graph View"))
