# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\editors\jrl.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 570)
        MainWindow.setMinimumSize(QtCore.QSize(600, 450))
        MainWindow.setStyleSheet("\n"
"    QTreeView {\n"
"    background-color: palette(base);\n"
"    alternate-background-color: palette(alternate-base);\n"
"    color: palette(text);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 3px;\n"
"    selection-background-color: palette(highlight);\n"
"    selection-color: palette(highlighted-text);\n"
"    show-decoration-selected: 1;\n"
"    }\n"
"    QTreeView::item {\n"
"    padding: 3px 4px;\n"
"    border-radius: 2px;\n"
"    }\n"
"    QTreeView::item:hover {\n"
"    background-color: palette(midlight);\n"
"    }\n"
"    QTreeView::branch {\n"
"    background: palette(base);\n"
"    }\n"
"    QSplitter::handle {\n"
"    background-color: palette(mid);\n"
"    }\n"
"    QSplitter::handle:vertical {\n"
"    height: 4px;\n"
"    }\n"
"    QGroupBox {\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 4px;\n"
"    margin-top: 8px;\n"
"    padding: 4px 2px 2px 2px;\n"
"    font-weight: bold;\n"
"    color: palette(window-text);\n"
"    }\n"
"    QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 4px;\n"
"    left: 8px;\n"
"    }\n"
"    QLineEdit {\n"
"    background-color: palette(base);\n"
"    color: palette(text);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 3px;\n"
"    padding: 2px 4px;\n"
"    }\n"
"    QLineEdit:focus {\n"
"    border: 1px solid palette(highlight);\n"
"    }\n"
"    QSpinBox, QDoubleSpinBox {\n"
"    background-color: palette(base);\n"
"    color: palette(text);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 3px;\n"
"    padding: 1px 3px;\n"
"    }\n"
"    QComboBox {\n"
"    background-color: palette(button);\n"
"    color: palette(button-text);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 3px;\n"
"    padding: 1px 6px;\n"
"    }\n"
"    QComboBox:hover {\n"
"    border: 1px solid palette(highlight);\n"
"    }\n"
"    QComboBox::drop-down {\n"
"    border: none;\n"
"    }\n"
"    QCheckBox {\n"
"    color: palette(window-text);\n"
"    spacing: 5px;\n"
"    }\n"
"    QCheckBox::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 2px;\n"
"    background-color: palette(base);\n"
"    }\n"
"    QCheckBox::indicator:checked {\n"
"    background-color: palette(highlight);\n"
"    border-color: palette(highlight);\n"
"    }\n"
"    QLabel {\n"
"    color: palette(window-text);\n"
"    }\n"
"    QPlainTextEdit {\n"
"    background-color: palette(base);\n"
"    color: palette(text);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"    }\n"
"    QPlainTextEdit:focus {\n"
"    border: 1px solid palette(highlight);\n"
"    }\n"
"    QPushButton {\n"
"    background-color: palette(button);\n"
"    color: palette(button-text);\n"
"    border: 1px solid palette(mid);\n"
"    border-radius: 3px;\n"
"    padding: 2px 8px;\n"
"    }\n"
"    QPushButton:hover {\n"
"    background-color: palette(midlight);\n"
"    }\n"
"    QPushButton:pressed {\n"
"    background-color: palette(dark);\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_main.setSpacing(4)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.filterBarLayout = QtWidgets.QHBoxLayout()
        self.filterBarLayout.setSpacing(4)
        self.filterBarLayout.setObjectName("filterBarLayout")
        self.filterLabel = QtWidgets.QLabel(self.centralwidget)
        self.filterLabel.setObjectName("filterLabel")
        self.filterBarLayout.addWidget(self.filterLabel)
        self.filterEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filterEdit.setClearButtonEnabled(True)
        self.filterEdit.setObjectName("filterEdit")
        self.filterBarLayout.addWidget(self.filterEdit)
        self.filterClearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.filterClearBtn.setMaximumSize(QtCore.QSize(28, 16777215))
        self.filterClearBtn.setFlat(True)
        self.filterClearBtn.setObjectName("filterClearBtn")
        self.filterBarLayout.addWidget(self.filterClearBtn)
        self.verticalLayout_main.addLayout(self.filterBarLayout)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.journalTree = RobustTreeView(self.splitter)
        self.journalTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.journalTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.journalTree.setAlternatingRowColors(True)
        self.journalTree.setHeaderHidden(True)
        self.journalTree.setObjectName("journalTree")
        self.questPages = QtWidgets.QStackedWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questPages.sizePolicy().hasHeightForWidth())
        self.questPages.setSizePolicy(sizePolicy)
        self.questPages.setObjectName("questPages")
        self.categoryPage = QtWidgets.QWidget()
        self.categoryPage.setObjectName("categoryPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.categoryPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.categoryPropsGroup = QtWidgets.QGroupBox(self.categoryPage)
        self.categoryPropsGroup.setObjectName("categoryPropsGroup")
        self.formLayout = QtWidgets.QFormLayout(self.categoryPropsGroup)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.categoryPropsGroup)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoryNameEdit = LocalizedStringLineEdit(self.categoryPropsGroup)
        self.categoryNameEdit.setMinimumSize(QtCore.QSize(0, 23))
        self.categoryNameEdit.setObjectName("categoryNameEdit")
        self.horizontalLayout.addWidget(self.categoryNameEdit)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.categoryPropsGroup)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.categoryTag = QtWidgets.QLineEdit(self.categoryPropsGroup)
        self.categoryTag.setObjectName("categoryTag")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.categoryTag)
        self.label_3 = QtWidgets.QLabel(self.categoryPropsGroup)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.categoryPlotSelect = ComboBox2DA(self.categoryPropsGroup)
        self.categoryPlotSelect.setObjectName("categoryPlotSelect")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.categoryPlotSelect)
        self.label_2 = QtWidgets.QLabel(self.categoryPropsGroup)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.categoryPlanetSelect = ComboBox2DA(self.categoryPropsGroup)
        self.categoryPlanetSelect.setObjectName("categoryPlanetSelect")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.categoryPlanetSelect)
        self.label_4 = QtWidgets.QLabel(self.categoryPropsGroup)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.categoryPrioritySelect = QtWidgets.QComboBox(self.categoryPropsGroup)
        self.categoryPrioritySelect.setObjectName("categoryPrioritySelect")
        self.categoryPrioritySelect.addItem("")
        self.categoryPrioritySelect.addItem("")
        self.categoryPrioritySelect.addItem("")
        self.categoryPrioritySelect.addItem("")
        self.categoryPrioritySelect.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.categoryPrioritySelect)
        self.horizontalLayout_2.addWidget(self.categoryPropsGroup)
        self.categoryNotesGroup = QtWidgets.QGroupBox(self.categoryPage)
        self.categoryNotesGroup.setObjectName("categoryNotesGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.categoryNotesGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.categoryCommentEdit = HTPlainTextEdit(self.categoryNotesGroup)
        self.categoryCommentEdit.setObjectName("categoryCommentEdit")
        self.verticalLayout_2.addWidget(self.categoryCommentEdit)
        self.horizontalLayout_2.addWidget(self.categoryNotesGroup)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.questPages.addWidget(self.categoryPage)
        self.entryPage = QtWidgets.QWidget()
        self.entryPage.setObjectName("entryPage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.entryPage)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.entryPropsGroup = QtWidgets.QGroupBox(self.entryPage)
        self.entryPropsGroup.setObjectName("entryPropsGroup")
        self.formLayout_2 = QtWidgets.QFormLayout(self.entryPropsGroup)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.entryPropsGroup)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.entryIdSpin = QtWidgets.QSpinBox(self.entryPropsGroup)
        self.entryIdSpin.setMinimumSize(QtCore.QSize(80, 0))
        self.entryIdSpin.setMinimum(0)
        self.entryIdSpin.setMaximum(2147483647)
        self.entryIdSpin.setObjectName("entryIdSpin")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.entryIdSpin)
        self.label_9 = QtWidgets.QLabel(self.entryPropsGroup)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.entryXpSpin = QtWidgets.QDoubleSpinBox(self.entryPropsGroup)
        self.entryXpSpin.setMinimum(0.0)
        self.entryXpSpin.setMaximum(1000.0)
        self.entryXpSpin.setObjectName("entryXpSpin")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.entryXpSpin)
        self.label_7 = QtWidgets.QLabel(self.entryPropsGroup)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.entryEndCheck = QtWidgets.QCheckBox(self.entryPropsGroup)
        self.entryEndCheck.setText("")
        self.entryEndCheck.setObjectName("entryEndCheck")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.entryEndCheck)
        self.horizontalLayout_3.addWidget(self.entryPropsGroup)
        self.entryTextGroup = QtWidgets.QGroupBox(self.entryPage)
        self.entryTextGroup.setObjectName("entryTextGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.entryTextGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.entryTextEdit = HTPlainTextEdit(self.entryTextGroup)
        self.entryTextEdit.setReadOnly(True)
        self.entryTextEdit.setObjectName("entryTextEdit")
        self.verticalLayout.addWidget(self.entryTextEdit)
        self.horizontalLayout_3.addWidget(self.entryTextGroup)
        self.questPages.addWidget(self.entryPage)
        self.verticalLayout_main.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionRevert = QtWidgets.QAction(MainWindow)
        self.actionRevert.setObjectName("actionRevert")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuNew.addAction(self.actionNew)
        self.menuNew.addAction(self.actionOpen)
        self.menuNew.addAction(self.actionSave)
        self.menuNew.addAction(self.actionSave_As)
        self.menuNew.addAction(self.actionRevert)
        self.menuNew.addSeparator()
        self.menuNew.addAction(self.actionSettings)
        self.menuNew.addSeparator()
        self.menuNew.addAction(self.actionExit)
        self.menubar.addAction(self.menuNew.menuAction())

        self.retranslateUi(MainWindow)
        self.questPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Journal Editor"))
        self.filterLabel.setText(_translate("MainWindow", "Filter:"))
        self.filterEdit.setPlaceholderText(_translate("MainWindow", "Search quests and entries..."))
        self.filterEdit.setToolTip(_translate("MainWindow", "Type to filter quests and entries. Right-click for filter options."))
        self.filterClearBtn.setText(_translate("MainWindow", "X"))
        self.filterClearBtn.setToolTip(_translate("MainWindow", "Clear filter"))
        self.categoryPropsGroup.setTitle(_translate("MainWindow", "Quest Properties"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.categoryNameEdit.setToolTip(_translate("MainWindow", "Name (GFF: Name): Display title of the quest in the journal. Localized\n"
"                  string. Shown in the quest list."))
        self.label_5.setText(_translate("MainWindow", "Tag:"))
        self.categoryTag.setToolTip(_translate("MainWindow", "Tag (GFF: Tag): Unique identifier for this quest. Scripts use\n"
"                AddJournalQuestEntry(\"Tag\", ID). Right-click to find all references."))
        self.label_3.setText(_translate("MainWindow", "Plot Index:"))
        self.categoryPlotSelect.setToolTip(_translate("MainWindow", "PlotIndex (GFF: PlotIndex): Row index into plot.2da. Legacy plot flag. INT32."))
        self.label_2.setText(_translate("MainWindow", "Planet ID:"))
        self.categoryPlanetSelect.setToolTip(_translate("MainWindow", "PlanetID (GFF: PlanetID): Row index into planet 2DA. Toolset metadata only.\n"
"                INT32."))
        self.label_4.setText(_translate("MainWindow", "Priority:"))
        self.categoryPrioritySelect.setToolTip(_translate("MainWindow", "Priority (GFF: Priority): Quest sort order. 0=Highest, 4=Lowest. UINT32."))
        self.categoryPrioritySelect.setItemText(0, _translate("MainWindow", "Highest"))
        self.categoryPrioritySelect.setItemText(1, _translate("MainWindow", "High"))
        self.categoryPrioritySelect.setItemText(2, _translate("MainWindow", "Medium"))
        self.categoryPrioritySelect.setItemText(3, _translate("MainWindow", "Low"))
        self.categoryPrioritySelect.setItemText(4, _translate("MainWindow", "Lowest"))
        self.categoryNotesGroup.setTitle(_translate("MainWindow", "Notes"))
        self.categoryCommentEdit.setToolTip(_translate("MainWindow", "Comment (GFF: Comment): Developer notes only. The game ignores this."))
        self.entryPropsGroup.setTitle(_translate("MainWindow", "Entry Properties"))
        self.label_8.setText(_translate("MainWindow", "ID:"))
        self.entryIdSpin.setToolTip(_translate("MainWindow", "ID (GFF: ID): State identifier. Scripts use AddJournalQuestEntry(\"Tag\", ID).\n"
"                UINT32."))
        self.label_9.setText(_translate("MainWindow", "XP Percentage:"))
        self.entryXpSpin.setToolTip(_translate("MainWindow", "XP_Percentage (GFF: XP_Percentage): XP reward multiplier. Float."))
        self.label_7.setText(_translate("MainWindow", "End:"))
        self.entryEndCheck.setToolTip(_translate("MainWindow", "End (GFF: End): Completes the quest when reached. BYTE 0/1."))
        self.entryTextGroup.setTitle(_translate("MainWindow", "Entry Text"))
        self.entryTextEdit.setToolTip(_translate("MainWindow", "Text (GFF: Text): Journal text shown to the player for this entry. Localized\n"
"                string. Double-click to edit."))
        self.menuNew.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionRevert.setText(_translate("MainWindow", "Revert"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings..."))
        self.actionSettings.setToolTip(_translate("MainWindow", "Configure Journal Editor filter and jump-to-resource behaviour"))
from toolset.gui.widgets.edit.combobox_2da import ComboBox2DA
from toolset.gui.widgets.edit.locstring import LocalizedStringLineEdit
from toolset.gui.widgets.edit.plaintext import HTPlainTextEdit
from utility.gui.qt.widgets.itemviews.treeview import RobustTreeView
