# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\editors\uti.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 323)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_preview = QtWidgets.QVBoxLayout()
        self.verticalLayout_preview.setObjectName("verticalLayout_preview")
        self.previewRenderer = ModelRenderer(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewRenderer.sizePolicy().hasHeightForWidth())
        self.previewRenderer.setSizePolicy(sizePolicy)
        self.previewRenderer.setMinimumSize(QtCore.QSize(200, 0))
        self.previewRenderer.setMouseTracking(True)
        self.previewRenderer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.previewRenderer.setObjectName("previewRenderer")
        self.verticalLayout_preview.addWidget(self.previewRenderer)
        self.itemModelInfoGroupBox = QtWidgets.QGroupBox(self.tab)
        self.itemModelInfoGroupBox.setCheckable(True)
        self.itemModelInfoGroupBox.setChecked(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemModelInfoGroupBox.sizePolicy().hasHeightForWidth())
        self.itemModelInfoGroupBox.setSizePolicy(sizePolicy)
        self.itemModelInfoGroupBox.setObjectName("itemModelInfoGroupBox")
        self.verticalLayout_itemModelInfo = QtWidgets.QVBoxLayout(self.itemModelInfoGroupBox)
        self.verticalLayout_itemModelInfo.setObjectName("verticalLayout_itemModelInfo")
        self.itemModelInfoSummaryLabel = QtWidgets.QLabel(self.itemModelInfoGroupBox)
        self.itemModelInfoSummaryLabel.setWordWrap(True)
        self.itemModelInfoSummaryLabel.setObjectName("itemModelInfoSummaryLabel")
        self.verticalLayout_itemModelInfo.addWidget(self.itemModelInfoSummaryLabel)
        self.itemModelInfoLabel = QtWidgets.QLabel(self.itemModelInfoGroupBox)
        self.itemModelInfoLabel.setText("")
        self.itemModelInfoLabel.setWordWrap(True)
        self.itemModelInfoLabel.setObjectName("itemModelInfoLabel")
        self.verticalLayout_itemModelInfo.addWidget(self.itemModelInfoLabel)
        self.verticalLayout_preview.addWidget(self.itemModelInfoGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_preview)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.tab)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.nameEdit = LocalizedStringLineEdit(self.tab)
        self.nameEdit.setMinimumSize(QtCore.QSize(0, 23))
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout_18.addWidget(self.nameEdit)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.tagLabel = QtWidgets.QLabel(self.tab)
        self.tagLabel.setObjectName("tagLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tagLabel)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tagEdit = QtWidgets.QLineEdit(self.tab)
        self.tagEdit.setObjectName("tagEdit")
        self.horizontalLayout_19.addWidget(self.tagEdit)
        self.tagGenerateButton = QtWidgets.QPushButton(self.tab)
        self.tagGenerateButton.setMaximumSize(QtCore.QSize(26, 16777215))
        self.tagGenerateButton.setObjectName("tagGenerateButton")
        self.horizontalLayout_19.addWidget(self.tagGenerateButton)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.resrefLabel = QtWidgets.QLabel(self.tab)
        self.resrefLabel.setObjectName("resrefLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.resrefLabel)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.resrefEdit = QtWidgets.QLineEdit(self.tab)
        self.resrefEdit.setMaxLength(16)
        self.resrefEdit.setObjectName("resrefEdit")
        self.horizontalLayout_20.addWidget(self.resrefEdit)
        self.resrefGenerateButton = QtWidgets.QPushButton(self.tab)
        self.resrefGenerateButton.setMaximumSize(QtCore.QSize(26, 16777215))
        self.resrefGenerateButton.setObjectName("resrefGenerateButton")
        self.horizontalLayout_20.addWidget(self.resrefGenerateButton)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_20)
        self.descriptionLabel = QtWidgets.QLabel(self.tab)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.descriptionLabel)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.descEdit = LocalizedStringLineEdit(self.tab)
        self.descEdit.setMinimumSize(QtCore.QSize(0, 23))
        self.descEdit.setObjectName("descEdit")
        self.horizontalLayout_21.addWidget(self.descEdit)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.baseItemLabel = QtWidgets.QLabel(self.tab)
        self.baseItemLabel.setObjectName("baseItemLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.baseItemLabel)
        self.baseSelect = ComboBox2DA(self.tab)
        self.baseSelect.setObjectName("baseSelect")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.baseSelect)
        self.costLabel = QtWidgets.QLabel(self.tab)
        self.costLabel.setObjectName("costLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.costLabel)
        self.costSpin = QtWidgets.QSpinBox(self.tab)
        self.costSpin.setMinimum(0)
        self.costSpin.setMaximum(2147483647)
        self.costSpin.setObjectName("costSpin")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.costSpin)
        self.addCostLabel = QtWidgets.QLabel(self.tab)
        self.addCostLabel.setObjectName("addCostLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.addCostLabel)
        self.additionalCostSpin = QtWidgets.QSpinBox(self.tab)
        self.additionalCostSpin.setMinimum(0)
        self.additionalCostSpin.setMaximum(2147483647)
        self.additionalCostSpin.setObjectName("additionalCostSpin")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.additionalCostSpin)
        self.upgradeLvlLabel = QtWidgets.QLabel(self.tab)
        self.upgradeLvlLabel.setObjectName("upgradeLvlLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.upgradeLvlLabel)
        self.upgradeSpin = QtWidgets.QSpinBox(self.tab)
        self.upgradeSpin.setMinimum(0)
        self.upgradeSpin.setMaximum(255)
        self.upgradeSpin.setObjectName("upgradeSpin")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.upgradeSpin)
        self.labelPlot = QtWidgets.QLabel(self.tab)
        self.labelPlot.setObjectName("labelPlot")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelPlot)
        self.plotCheckbox = QtWidgets.QCheckBox(self.tab)
        self.plotCheckbox.setText("")
        self.plotCheckbox.setObjectName("plotCheckbox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.plotCheckbox)
        self.labelCharges = QtWidgets.QLabel(self.tab)
        self.labelCharges.setObjectName("labelCharges")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.labelCharges)
        self.chargesSpin = QtWidgets.QSpinBox(self.tab)
        self.chargesSpin.setMinimum(0)
        self.chargesSpin.setMaximum(255)
        self.chargesSpin.setObjectName("chargesSpin")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.chargesSpin)
        self.labelStack = QtWidgets.QLabel(self.tab)
        self.labelStack.setObjectName("labelStack")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.labelStack)
        self.stackSpin = QtWidgets.QSpinBox(self.tab)
        self.stackSpin.setMinimum(1)
        self.stackSpin.setMaximum(255)
        self.stackSpin.setObjectName("stackSpin")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.stackSpin)
        self.labelModelVar = QtWidgets.QLabel(self.tab)
        self.labelModelVar.setObjectName("labelModelVar")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.labelModelVar)
        self.modelVarSpin = QtWidgets.QSpinBox(self.tab)
        self.modelVarSpin.setMinimum(0)
        self.modelVarSpin.setMaximum(255)
        self.modelVarSpin.setObjectName("modelVarSpin")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.modelVarSpin)
        self.labelBodyVar = QtWidgets.QLabel(self.tab)
        self.labelBodyVar.setObjectName("labelBodyVar")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.labelBodyVar)
        self.bodyVarSpin = QtWidgets.QSpinBox(self.tab)
        self.bodyVarSpin.setMinimum(0)
        self.bodyVarSpin.setMaximum(255)
        self.bodyVarSpin.setObjectName("bodyVarSpin")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.bodyVarSpin)
        self.labelTextureVar = QtWidgets.QLabel(self.tab)
        self.labelTextureVar.setObjectName("labelTextureVar")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.labelTextureVar)
        self.textureVarSpin = QtWidgets.QSpinBox(self.tab)
        self.textureVarSpin.setMinimum(0)
        self.textureVarSpin.setMaximum(255)
        self.textureVarSpin.setObjectName("textureVarSpin")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.textureVarSpin)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_icon = QtWidgets.QVBoxLayout()
        self.verticalLayout_icon.setObjectName("verticalLayout_icon")
        self.iconGroupBox = QtWidgets.QGroupBox(self.tab)
        self.iconGroupBox.setMaximumSize(QtCore.QSize(84, 16777215))
        self.iconGroupBox.setObjectName("iconGroupBox")
        self.gridLayout_icon = QtWidgets.QGridLayout(self.iconGroupBox)
        self.gridLayout_icon.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_icon.setSpacing(3)
        self.gridLayout_icon.setObjectName("gridLayout_icon")
        self.iconLabel = QtWidgets.QLabel(self.iconGroupBox)
        self.iconLabel.setMinimumSize(QtCore.QSize(64, 64))
        self.iconLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.iconLabel.setText("")
        self.iconLabel.setScaledContents(True)
        self.iconLabel.setObjectName("iconLabel")
        self.gridLayout_icon.addWidget(self.iconLabel, 0, 0, 1, 1)
        self.verticalLayout_icon.addWidget(self.iconGroupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_icon)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.availPropLabel = QtWidgets.QLabel(self.tab_2)
        self.availPropLabel.setObjectName("availPropLabel")
        self.verticalLayout_3.addWidget(self.availPropLabel)
        self.availablePropertyList = QtWidgets.QTreeWidget(self.tab_2)
        self.availablePropertyList.setObjectName("availablePropertyList")
        self.availablePropertyList.headerItem().setText(0, "1")
        self.availablePropertyList.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.availablePropertyList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.addPropertyButton = QtWidgets.QPushButton(self.tab_2)
        self.addPropertyButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.addPropertyButton.setObjectName("addPropertyButton")
        self.verticalLayout_2.addWidget(self.addPropertyButton)
        self.removePropertyButton = QtWidgets.QPushButton(self.tab_2)
        self.removePropertyButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.removePropertyButton.setObjectName("removePropertyButton")
        self.verticalLayout_2.addWidget(self.removePropertyButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.propertyLabel = QtWidgets.QLabel(self.tab_2)
        self.propertyLabel.setObjectName("propertyLabel")
        self.verticalLayout_4.addWidget(self.propertyLabel)
        self.assignedPropertiesList = QtWidgets.QListWidget(self.tab_2)
        self.assignedPropertiesList.setObjectName("assignedPropertiesList")
        self.verticalLayout_4.addWidget(self.assignedPropertiesList)
        self.editPropertyButton = QtWidgets.QPushButton(self.tab_2)
        self.editPropertyButton.setObjectName("editPropertyButton")
        self.verticalLayout_4.addWidget(self.editPropertyButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.commentsTab = QtWidgets.QWidget()
        self.commentsTab.setObjectName("commentsTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.commentsTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.commentsEdit = QtWidgets.QPlainTextEdit(self.commentsTab)
        self.commentsEdit.setObjectName("commentsEdit")
        self.gridLayout_2.addWidget(self.commentsEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.commentsTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionRevert = QtWidgets.QAction(MainWindow)
        self.actionRevert.setObjectName("actionRevert")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionRevert)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.itemModelInfoGroupBox.setTitle(_translate("MainWindow", "Model Info"))
        self.itemModelInfoSummaryLabel.setToolTip(_translate("MainWindow", "Summary of the item\'s 3D model. Expand to see full model path and texture\n"
"                 info. Display-only; change Base Item or Model Variation to change the model. Not\n"
"                 stored in the GFF."))
        self.nameLabel.setText(_translate("MainWindow", "Name:"))
        self.nameEdit.setToolTip(_translate("MainWindow", "Name (GFF: LocalizedName). CExoLocString. The displayed name of the item in\n"
"                inventory, stores, and dialogue. Engine reads via ReadFieldCExoLocString in\n"
"                CSWSItem::LoadDataFromGff. Modders: set a custom name or leave\n"
"                empty to use the base item\'s default from baseitems.2da. Shown in the item\n"
"                description panel and store/container UI."))
        self.tagLabel.setText(_translate("MainWindow", "Tag:"))
        self.tagEdit.setToolTip(_translate("MainWindow", "Tag (GFF: Tag). CExoString. Unique identifier for this item when placed in\n"
"                the module. Engine reads via ReadFieldCExoString in LoadDataFromGff. Scripts use\n"
"                GetItemByTag to target this item. Modders: leave blank for\n"
"                stackable/generic items; set a tag for scripted references. Duplicate tags in the\n"
"                same area can cause wrong item to be targeted."))
        self.tagGenerateButton.setToolTip(_translate("MainWindow", "Generate tag from ResRef. Copies the Template ResRef into the Tag field so\n"
"                they stay in sync. Use when you need to reference this item by tag in scripts; keep\n"
"                Tag unique per area."))
        self.tagGenerateButton.setText(_translate("MainWindow", "-"))
        self.resrefLabel.setText(_translate("MainWindow", "ResRef:"))
        self.resrefEdit.setToolTip(_translate("MainWindow", "Template ResRef (GFF: TemplateResRef). ResRef (max 16 characters) of this\n"
"                item template; .uti extension implied. The engine stores ResRefs in 16 bytes. When\n"
"                the game loads an item it uses this to find the UTI\n"
"                file. Modders: must match the .uti filename; used by stores, loot tables, and\n"
"                GiveItem. Mismatch can cause missing or wrong item data."))
        self.resrefGenerateButton.setToolTip(_translate("MainWindow", "Generate ResRef from Tag. Copies the Tag into the Template ResRef field (max\n"
"                16 characters). ResRef should match the UTI filename for the game to load the item\n"
"                correctly."))
        self.resrefGenerateButton.setText(_translate("MainWindow", "-"))
        self.descriptionLabel.setText(_translate("MainWindow", "Description:"))
        self.descEdit.setToolTip(_translate("MainWindow", "Description (GFF: DescIdentified). CExoLocString. Shown when the player\n"
"                examines an identified item. Engine reads via ReadFieldCExoLocString in\n"
"                LoadDataFromGff. \"Description\" (unidentified) is also read;\n"
"                DescIdentified is the main one shown after identification. Modders: use for lore,\n"
"                usage hints, or flavor text."))
        self.baseItemLabel.setText(_translate("MainWindow", "Base Item:"))
        self.baseSelect.setToolTip(_translate("MainWindow", "Base Item (GFF: BaseItem). INT32. Engine reads via ReadFieldINT in\n"
"              LoadDataFromGff. Row index into baseitems.2da; determines category\n"
"              (weapon, armor, usable), equip slots, model type, and default stats. Modders: must be\n"
"              a valid row; invalid indices can cause load failures or wrong visuals. Changing this\n"
"              changes the item\'s core behavior (e.g. blaster vs. lightsaber)."))
        self.costLabel.setText(_translate("MainWindow", "Cost:"))
        self.costSpin.setToolTip(_translate("MainWindow", "Cost (GFF: Cost). Base sale/purchase price in credits. Stored as DWORD\n"
"              (0–4294967295); UI caps at 2147483647. The engine does not read this field in\n"
"              LoadDataFromGff; it is written by SaveItem when saving. Store and\n"
"              barter typically use base item pricing plus AddCost (which the engine does read).\n"
"              Modders: set for toolset consistency and documentation; to affect in-game price, use\n"
"              Additional Cost. 0 = free. Very high values may display oddly in some UIs."))
        self.addCostLabel.setText(_translate("MainWindow", "Additional Cost:"))
        self.additionalCostSpin.setToolTip(_translate("MainWindow", "Additional Cost (GFF: AddCost). DWORD. Engine reads via ReadFieldDWORD in\n"
"              LoadDataFromGff. Extra credits added to base cost; combined with\n"
"              base item pricing for final store price. Modders: increase for upgraded or\n"
"              high-property items. Valid range 0–4294967295; UI caps at 2147483647."))
        self.upgradeLvlLabel.setText(_translate("MainWindow", "Upgrade Level:"))
        self.upgradeSpin.setToolTip(_translate("MainWindow", "Upgrade Level (GFF: Upgrades). DWORD in engine (ReadFieldDWORD in\n"
"              LoadDataFromGff). K1: bitfield for which upgrade slots are filled.\n"
"              K2: often used as upgrade tier (0–255). UI shows 0–255. Modders: must match base item;\n"
"              invalid values can break upgrade slots or display."))
        self.labelPlot.setText(_translate("MainWindow", "Plot:"))
        self.plotCheckbox.setToolTip(_translate("MainWindow", "Plot (GFF: Plot). Boolean. If set, the item cannot be dropped or sold. Engine\n"
"              reads via ReadFieldCExoString/BOOL in LoadDataFromGff. Used for key quest items."))
        self.labelCharges.setText(_translate("MainWindow", "Charges:"))
        self.chargesSpin.setToolTip(_translate("MainWindow", "Charges (GFF: Charges). Number of uses remaining for usable items (e.g.\n"
"              medpacs). Engine reads in LoadDataFromGff."))
        self.labelStack.setText(_translate("MainWindow", "Stack Size:"))
        self.stackSpin.setToolTip(_translate("MainWindow", "Stack Size (GFF: StackSize). Number of items in this stack. Engine reads in\n"
"              LoadDataFromGff."))
        self.labelModelVar.setText(_translate("MainWindow", "Model Variation:"))
        self.modelVarSpin.setToolTip(_translate("MainWindow", "Model Variation (GFF: ModelVariation). Picks which model variant is used for\n"
"              this base item. Affects 3D preview."))
        self.labelBodyVar.setText(_translate("MainWindow", "Body Variation:"))
        self.bodyVarSpin.setToolTip(_translate("MainWindow", "Body Variation. Body part variant for the model."))
        self.labelTextureVar.setText(_translate("MainWindow", "Texture Variation:"))
        self.textureVarSpin.setToolTip(_translate("MainWindow", "Texture Variation (GFF: TextureVar). Texture variant for the model. Affects 3D\n"
"              preview."))
        self.iconGroupBox.setTitle(_translate("MainWindow", "Icon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General"))
        self.availPropLabel.setText(_translate("MainWindow", "Available Properties"))
        self.availPropLabel.setToolTip(_translate("MainWindow", "Available properties from itemprops.2da (and related 2DAs). Add properties to\n"
"              define enchantments, damage bonuses, and special effects. The engine reads assigned\n"
"              properties from GFF PropertiesList; each entry has PropertyName (WORD), Subtype\n"
"              (WORD),\n"
"              CostTable (BYTE), CostValue (WORD), Param1, Param1Value, ChanceAppear (BYTE), Useable\n"
"              (BYTE).\n"
"              Use the arrow buttons to assign."))
        self.addPropertyButton.setToolTip(_translate("MainWindow", "Add the selected available property to this item. Appends an entry to the GFF\n"
"              PropertiesList; the engine reads these in LoadDataFromGff. Use Edit\n"
"              Property to set Subtype, CostValue, Param1, Param1Value, ChanceAppear, etc."))
        self.addPropertyButton.setText(_translate("MainWindow", "->"))
        self.removePropertyButton.setToolTip(_translate("MainWindow", "Remove the selected property from this item. Deletes the entry from the GFF\n"
"              PropertiesList. The item will no longer have that enchantment or effect in-game."))
        self.removePropertyButton.setText(_translate("MainWindow", "<-"))
        self.propertyLabel.setText(_translate("MainWindow", "Assigned Properties"))
        self.propertyLabel.setToolTip(_translate("MainWindow", "Assigned properties (GFF: PropertiesList). The engine reads this list in\n"
"              LoadDataFromGff via GetList(\"PropertiesList\"); each element has\n"
"              PropertyName (WORD), Subtype (WORD), CostTable (BYTE), CostValue (WORD), Param1,\n"
"              Param1Value (BYTE), ChanceAppear (BYTE), Useable (BYTE). Edit Property to adjust\n"
"              values. Order can affect display and some game logic."))
        self.assignedPropertiesList.setToolTip(_translate("MainWindow", "List of item properties on this item. Each row is one entry in GFF\n"
"              PropertiesList. Select a row and click Edit Property to change Subtype, CostValue,\n"
"              Param1, Param1Value, ChanceAppear, and other fields. The game applies these effects\n"
"              when the item is equipped or used."))
        self.editPropertyButton.setToolTip(_translate("MainWindow", "Open the property editor for the selected assigned property. Lets you set\n"
"              Subtype, CostTable, CostValue, Param1, Param1Value, ChanceAppear (0–100), Useable, and\n"
"              other fields. Required for configuring damage types, bonuses, and effect parameters."))
        self.editPropertyButton.setText(_translate("MainWindow", "Edit Property"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Properties"))
        self.commentsEdit.setToolTip(_translate("MainWindow", "Comments (GFF: Comment). CExoString. Developer notes only—the game engine never\n"
"            reads or displays this. Use for mod documentation, credits, or internal notes. No length\n"
"            limit in GFF."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.commentsTab), _translate("MainWindow", "Comments"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionRevert.setText(_translate("MainWindow", "Revert"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
from toolset.gui.widgets.edit.combobox_2da import ComboBox2DA
from toolset.gui.widgets.edit.locstring import LocalizedStringLineEdit
from toolset.gui.widgets.renderer.model import ModelRenderer
