# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\better_message_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.iconLabel = QtWidgets.QLabel(Dialog)
        self.iconLabel.setText("")
        self.iconLabel.setAlignment(QtCore.Qt.AlignTop|QtCore.Qt.AlignLeft)
        self.iconLabel.setScaledContents(False)
        self.iconLabel.setObjectName("iconLabel")
        self.verticalLayout.addWidget(self.iconLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.messageLabel = QtWidgets.QLabel(Dialog)
        self.messageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setObjectName("messageLabel")
        self.verticalLayout.addWidget(self.messageLabel)
        self.toggleDetailsButton = QtWidgets.QPushButton(Dialog)
        self.toggleDetailsButton.setCheckable(True)
        self.toggleDetailsButton.setVisible(False)
        self.toggleDetailsButton.setObjectName("toggleDetailsButton")
        self.verticalLayout.addWidget(self.toggleDetailsButton)
        self.detailedTextWidget = QtWidgets.QTextEdit(Dialog)
        self.detailedTextWidget.setReadOnly(True)
        self.detailedTextWidget.setVisible(False)
        self.detailedTextWidget.setObjectName("detailedTextWidget")
        self.verticalLayout.addWidget(self.detailedTextWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.messageLabel.setText(_translate("Dialog", "Message"))
        self.toggleDetailsButton.setText(_translate("Dialog", "Show Details..."))
