# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\select_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setContentsMargins(10, 10, 10, 10)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.fetchReleasesButton = QtWidgets.QPushButton(Dialog)
        self.fetchReleasesButton.setMinimumSize(QtCore.QSize(780, 50))
        self.fetchReleasesButton.setMaximumSize(QtCore.QSize(780, 50))
        self.fetchReleasesButton.setObjectName("fetchReleasesButton")
        self.mainLayout.addWidget(self.fetchReleasesButton)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.forkLabel = QtWidgets.QLabel(Dialog)
        self.forkLabel.setObjectName("forkLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.forkLabel)
        self.forkComboBox = QtWidgets.QComboBox(Dialog)
        self.forkComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.forkComboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.forkComboBox.setObjectName("forkComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.forkComboBox)
        self.releaseLabel = QtWidgets.QLabel(Dialog)
        self.releaseLabel.setObjectName("releaseLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.releaseLabel)
        self.releaseComboBox = QtWidgets.QComboBox(Dialog)
        self.releaseComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.releaseComboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.releaseComboBox.setObjectName("releaseComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.releaseComboBox)
        self.mainLayout.addLayout(self.formLayout)
        self.preReleaseCheckbox = QtWidgets.QCheckBox(Dialog)
        self.preReleaseCheckbox.setObjectName("preReleaseCheckbox")
        self.mainLayout.addWidget(self.preReleaseCheckbox)
        self.installSelectedButton = QtWidgets.QPushButton(Dialog)
        self.installSelectedButton.setMinimumSize(QtCore.QSize(150, 30))
        self.installSelectedButton.setMaximumSize(QtCore.QSize(150, 30))
        self.installSelectedButton.setObjectName("installSelectedButton")
        self.mainLayout.addWidget(self.installSelectedButton)
        self.changeLogEdit = QtWidgets.QTextEdit(Dialog)
        self.changeLogEdit.setReadOnly(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.changeLogEdit.setFont(font)
        self.changeLogEdit.setObjectName("changeLogEdit")
        self.mainLayout.addWidget(self.changeLogEdit)
        self.updateLatestButton = QtWidgets.QPushButton(Dialog)
        self.updateLatestButton.setMinimumSize(QtCore.QSize(780, 50))
        self.updateLatestButton.setMaximumSize(QtCore.QSize(780, 50))
        self.updateLatestButton.setObjectName("updateLatestButton")
        self.mainLayout.addWidget(self.updateLatestButton)
        self.currentVersionLayout = QtWidgets.QHBoxLayout()
        self.currentVersionLayout.setObjectName("currentVersionLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.currentVersionLayout.addItem(spacerItem)
        self.currentVersionLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.currentVersionLabel.setFont(font)
        self.currentVersionLabel.setObjectName("currentVersionLabel")
        self.currentVersionLayout.addWidget(self.currentVersionLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.currentVersionLayout.addItem(spacerItem1)
        self.mainLayout.addLayout(self.currentVersionLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Update Application"))
        self.fetchReleasesButton.setText(_translate("Dialog", "Fetch Releases"))
        self.forkLabel.setText(_translate("Dialog", "Select Fork:"))
        self.releaseLabel.setText(_translate("Dialog", "Select Release:"))
        self.preReleaseCheckbox.setText(_translate("Dialog", "Include Pre-releases"))
        self.installSelectedButton.setText(_translate("Dialog", "Install Selected"))
        self.updateLatestButton.setText(_translate("Dialog", "Update to Latest"))
        self.currentVersionLabel.setText(_translate("Dialog", "Holocron Toolset Current Version: "))
