# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\walkmesh_obstacle_properties.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.positionLabel = QtWidgets.QLabel(Dialog)
        self.positionLabel.setObjectName("positionLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.positionLabel)
        self.positionLayout = QtWidgets.QHBoxLayout()
        self.positionLayout.setObjectName("positionLayout")
        self.posX = QtWidgets.QDoubleSpinBox(Dialog)
        self.posX.setObjectName("posX")
        self.positionLayout.addWidget(self.posX)
        self.posY = QtWidgets.QDoubleSpinBox(Dialog)
        self.posY.setObjectName("posY")
        self.positionLayout.addWidget(self.posY)
        self.posZ = QtWidgets.QDoubleSpinBox(Dialog)
        self.posZ.setObjectName("posZ")
        self.positionLayout.addWidget(self.posZ)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.positionLayout)
        self.radiusLabel = QtWidgets.QLabel(Dialog)
        self.radiusLabel.setObjectName("radiusLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radiusLabel)
        self.radiusSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.radiusSpinBox.setObjectName("radiusSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radiusSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.buttonLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        self.okButton.clicked.connect(Dialog.accept) # type: ignore
        self.cancelButton.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Obstacle Properties"))
        self.positionLabel.setText(_translate("Dialog", "Position (X, Y, Z):"))
        self.radiusLabel.setText(_translate("Dialog", "Radius:"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
