# Form implementation generated from reading ui file '..\ui\widgets\settings\blender_settings.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=Form)
        self.titleLabel.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setObjectName("pathLayout")
        self.pathLabel = QtWidgets.QLabel(parent=Form)
        self.pathLabel.setObjectName("pathLabel")
        self.pathLayout.addWidget(self.pathLabel)
        self.pathEdit = QtWidgets.QLineEdit(parent=Form)
        self.pathEdit.setObjectName("pathEdit")
        self.pathLayout.addWidget(self.pathEdit)
        self.browseButton = QtWidgets.QPushButton(parent=Form)
        self.browseButton.setObjectName("browseButton")
        self.pathLayout.addWidget(self.browseButton)
        self.detectButton = QtWidgets.QPushButton(parent=Form)
        self.detectButton.setObjectName("detectButton")
        self.pathLayout.addWidget(self.detectButton)
        self.verticalLayout.addLayout(self.pathLayout)
        self.statusLabel = QtWidgets.QLabel(parent=Form)
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.installKotorblenderButton = QtWidgets.QPushButton(parent=Form)
        self.installKotorblenderButton.setVisible(False)
        self.installKotorblenderButton.setObjectName("installKotorblenderButton")
        self.verticalLayout.addWidget(self.installKotorblenderButton)
        self.preferBlenderCheckbox = QtWidgets.QCheckBox(parent=Form)
        self.preferBlenderCheckbox.setObjectName("preferBlenderCheckbox")
        self.verticalLayout.addWidget(self.preferBlenderCheckbox)
        self.rememberCheckbox = QtWidgets.QCheckBox(parent=Form)
        self.rememberCheckbox.setObjectName("rememberCheckbox")
        self.verticalLayout.addWidget(self.rememberCheckbox)
        self.portLayout = QtWidgets.QHBoxLayout()
        self.portLayout.setObjectName("portLayout")
        self.portLabel = QtWidgets.QLabel(parent=Form)
        self.portLabel.setObjectName("portLabel")
        self.portLayout.addWidget(self.portLabel)
        self.portSpinBox = QtWidgets.QSpinBox(parent=Form)
        self.portSpinBox.setMinimum(1024)
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setProperty("value", 7531)
        self.portSpinBox.setObjectName("portSpinBox")
        self.portLayout.addWidget(self.portSpinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.portLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.portLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLabel.setText(_translate("Form", "<b>Blender Integration</b>"))
        self.pathLabel.setText(_translate("Form", "Blender Path:"))
        self.pathEdit.setPlaceholderText(_translate("Form", "Auto-detect"))
        self.browseButton.setText(_translate("Form", "Browse..."))
        self.detectButton.setText(_translate("Form", "Detect"))
        self.installKotorblenderButton.setText(_translate("Form", "Install kotorblender"))
        self.preferBlenderCheckbox.setText(_translate("Form", "Prefer Blender when available"))
        self.preferBlenderCheckbox.setToolTip(_translate("Form", "Automatically use Blender for Module Designer, GIT Editor, etc."))
        self.rememberCheckbox.setText(_translate("Form", "Remember editor choice"))
        self.rememberCheckbox.setToolTip(_translate("Form", "Don\'t ask which editor to use each time"))
        self.portLabel.setText(_translate("Form", "IPC Port:"))
