# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\add_room.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.modelLabel = QtWidgets.QLabel(Dialog)
        self.modelLabel.setObjectName("modelLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.modelLabel)
        self.modelInput = QtWidgets.QLineEdit(Dialog)
        self.modelInput.setObjectName("modelInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.modelInput)
        self.xLabel = QtWidgets.QLabel(Dialog)
        self.xLabel.setObjectName("xLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.xLabel)
        self.xSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.xSpin.setDecimals(6)
        self.xSpin.setMinimum(-999999.0)
        self.xSpin.setMaximum(999999.0)
        self.xSpin.setObjectName("xSpin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xSpin)
        self.yLabel = QtWidgets.QLabel(Dialog)
        self.yLabel.setObjectName("yLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yLabel)
        self.ySpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.ySpin.setDecimals(6)
        self.ySpin.setMinimum(-999999.0)
        self.ySpin.setMaximum(999999.0)
        self.ySpin.setObjectName("ySpin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ySpin)
        self.zLabel = QtWidgets.QLabel(Dialog)
        self.zLabel.setObjectName("zLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.zLabel)
        self.zSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.zSpin.setDecimals(6)
        self.zSpin.setMinimum(-999999.0)
        self.zSpin.setMaximum(999999.0)
        self.zSpin.setObjectName("zSpin")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zSpin)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Room"))
        self.modelLabel.setText(_translate("Dialog", "Model:"))
        self.xLabel.setText(_translate("Dialog", "X:"))
        self.yLabel.setText(_translate("Dialog", "Y:"))
        self.zLabel.setText(_translate("Dialog", "Z:"))
