# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\async_loader.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(260, 40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(260, 40))
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.mainTaskText = QtWidgets.QLabel(Dialog)
        self.mainTaskText.setText("")
        self.mainTaskText.setAlignment(QtCore.Qt.AlignCenter)
        self.mainTaskText.setObjectName("mainTaskText")
        self.mainLayout.addWidget(self.mainTaskText)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setMinimumSize(QtCore.QSize(220, 20))
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setObjectName("progressBar")
        self.mainLayout.addWidget(self.progressBar)
        self.subTaskText = QtWidgets.QLabel(Dialog)
        self.subTaskText.setText("")
        self.subTaskText.setAlignment(QtCore.Qt.AlignCenter)
        self.subTaskText.setObjectName("subTaskText")
        self.mainLayout.addWidget(self.subTaskText)
        self.taskProgressText = QtWidgets.QLabel(Dialog)
        self.taskProgressText.setText("")
        self.taskProgressText.setAlignment(QtCore.Qt.AlignCenter)
        self.taskProgressText.setObjectName("taskProgressText")
        self.mainLayout.addWidget(self.taskProgressText)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass
