# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\batch_processor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setContentsMargins(9, 9, 9, 9)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.audioLayout = QtWidgets.QHBoxLayout()
        self.audioLayout.setSpacing(6)
        self.audioLayout.setObjectName("audioLayout")
        self.audioList = QtWidgets.QListWidget(Dialog)
        self.audioList.setObjectName("audioList")
        self.audioLayout.addWidget(self.audioList)
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setSpacing(6)
        self.buttonLayout.setObjectName("buttonLayout")
        self.addAudioBtn = QtWidgets.QPushButton(Dialog)
        self.addAudioBtn.setObjectName("addAudioBtn")
        self.buttonLayout.addWidget(self.addAudioBtn)
        self.removeAudioBtn = QtWidgets.QPushButton(Dialog)
        self.removeAudioBtn.setObjectName("removeAudioBtn")
        self.buttonLayout.addWidget(self.removeAudioBtn)
        self.clearAudioBtn = QtWidgets.QPushButton(Dialog)
        self.clearAudioBtn.setObjectName("clearAudioBtn")
        self.buttonLayout.addWidget(self.clearAudioBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.buttonLayout.addItem(spacerItem)
        self.audioLayout.addLayout(self.buttonLayout)
        self.mainLayout.addLayout(self.audioLayout)
        self.outputLayout = QtWidgets.QHBoxLayout()
        self.outputLayout.setSpacing(6)
        self.outputLayout.setObjectName("outputLayout")
        self.outputLabel = QtWidgets.QLabel(Dialog)
        self.outputLabel.setObjectName("outputLabel")
        self.outputLayout.addWidget(self.outputLabel)
        self.outputPath = QtWidgets.QLineEdit(Dialog)
        self.outputPath.setReadOnly(True)
        self.outputPath.setObjectName("outputPath")
        self.outputLayout.addWidget(self.outputPath)
        self.browseBtn = QtWidgets.QPushButton(Dialog)
        self.browseBtn.setObjectName("browseBtn")
        self.outputLayout.addWidget(self.browseBtn)
        self.mainLayout.addLayout(self.outputLayout)
        self.processBtn = QtWidgets.QPushButton(Dialog)
        self.processBtn.setObjectName("processBtn")
        self.mainLayout.addWidget(self.processBtn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Batch LIP Generator"))
        self.audioList.setToolTip(_translate("Dialog", "List of WAV files to process"))
        self.addAudioBtn.setText(_translate("Dialog", "Add Files..."))
        self.removeAudioBtn.setText(_translate("Dialog", "Remove Selected"))
        self.clearAudioBtn.setText(_translate("Dialog", "Clear All"))
        self.outputLabel.setText(_translate("Dialog", "Output Directory:"))
        self.outputPath.setToolTip(_translate("Dialog", "Directory where LIP files will be saved"))
        self.browseBtn.setText(_translate("Dialog", "Browse..."))
        self.processBtn.setText(_translate("Dialog", "Process Files"))
