# Form implementation generated from reading ui file '..\ui\dialogs\blender_choice.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 600)
        Dialog.setMinimumSize(QtCore.QSize(500, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoFrame = QtWidgets.QFrame(parent=Dialog)
        self.infoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.infoFrame.setObjectName("infoFrame")
        self.infoLayout = QtWidgets.QVBoxLayout(self.infoFrame)
        self.infoLayout.setObjectName("infoLayout")
        self.verticalLayout.addWidget(self.infoFrame)
        self.questionLabel = QtWidgets.QLabel(parent=Dialog)
        self.questionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.questionLabel.setObjectName("questionLabel")
        self.verticalLayout.addWidget(self.questionLabel)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setSpacing(16)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.blenderButton = QtWidgets.QPushButton(parent=Dialog)
        self.blenderButton.setMinimumSize(QtCore.QSize(0, 60))
        self.blenderButton.setObjectName("blenderButton")
        self.buttonsLayout.addWidget(self.blenderButton)
        self.builtinButton = QtWidgets.QPushButton(parent=Dialog)
        self.builtinButton.setMinimumSize(QtCore.QSize(0, 60))
        self.builtinButton.setObjectName("builtinButton")
        self.buttonsLayout.addWidget(self.builtinButton)
        self.verticalLayout.addLayout(self.buttonsLayout)
        self.comparisonLabel = QtWidgets.QLabel(parent=Dialog)
        self.comparisonLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.comparisonLabel.setObjectName("comparisonLabel")
        self.verticalLayout.addWidget(self.comparisonLabel)
        self.rememberCheckbox = QtWidgets.QCheckBox(parent=Dialog)
        self.rememberCheckbox.setObjectName("rememberCheckbox")
        self.verticalLayout.addWidget(self.rememberCheckbox)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout.addWidget(self.cancelButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Choose Editor"))
        self.questionLabel.setText(_translate("Dialog", "How would you like to open the Module Designer?"))
        self.blenderButton.setText(_translate("Dialog", "Open in Blender\n"
"(Recommended)"))
        self.builtinButton.setText(_translate("Dialog", "Use Built-in Editor"))
        self.builtinButton.setToolTip(_translate("Dialog", "Use the built-in PyKotorGL renderer.\n"
"Integrated experience, no external application needed."))
        self.comparisonLabel.setText(_translate("Dialog", "<table cellspacing=\'8\'>\n"
"<tr><th align=\'left\'></th><th>Blender</th><th>Built-in</th></tr>\n"
"<tr><td>Performance</td><td>⭐⭐⭐</td><td>⭐</td></tr>\n"
"<tr><td>3D Navigation</td><td>⭐⭐⭐</td><td>⭐⭐</td></tr>\n"
"<tr><td>Model Editing</td><td>⭐⭐⭐</td><td>❌</td></tr>\n"
"<tr><td>Lightmap Baking</td><td>⭐⭐⭐</td><td>❌</td></tr>\n"
"<tr><td>Integration</td><td>⭐⭐</td><td>⭐⭐⭐</td></tr>\n"
"</table>"))
        self.comparisonLabel.setStyleSheet(_translate("Dialog", "color: #666; font-size: 11px;"))
        self.rememberCheckbox.setText(_translate("Dialog", "Remember my choice"))
        self.rememberCheckbox.setToolTip(_translate("Dialog", "Don\'t show this dialog again. You can change this in Settings."))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
