# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\door_hook_properties.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setContentsMargins(16, 16, 16, 16)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.roomLayout = QtWidgets.QHBoxLayout()
        self.roomLayout.setObjectName("roomLayout")
        self.roomLabel = QtWidgets.QLabel(Dialog)
        self.roomLabel.setObjectName("roomLabel")
        self.roomLayout.addWidget(self.roomLabel)
        self.roomInput = QtWidgets.QLineEdit(Dialog)
        self.roomInput.setText("")
        self.roomInput.setObjectName("roomInput")
        self.roomLayout.addWidget(self.roomInput)
        self.mainLayout.addLayout(self.roomLayout)
        self.doorLayout = QtWidgets.QHBoxLayout()
        self.doorLayout.setObjectName("doorLayout")
        self.doorLabel = QtWidgets.QLabel(Dialog)
        self.doorLabel.setObjectName("doorLabel")
        self.doorLayout.addWidget(self.doorLabel)
        self.doorInput = QtWidgets.QLineEdit(Dialog)
        self.doorInput.setText("")
        self.doorInput.setObjectName("doorInput")
        self.doorLayout.addWidget(self.doorInput)
        self.mainLayout.addLayout(self.doorLayout)
        self.positionLayout = QtWidgets.QHBoxLayout()
        self.positionLayout.setObjectName("positionLayout")
        self.positionLabel = QtWidgets.QLabel(Dialog)
        self.positionLabel.setObjectName("positionLabel")
        self.positionLayout.addWidget(self.positionLabel)
        self.xLabel = QtWidgets.QLabel(Dialog)
        self.xLabel.setObjectName("xLabel")
        self.positionLayout.addWidget(self.xLabel)
        self.xSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.xSpin.setMinimum(-10000.0)
        self.xSpin.setMaximum(10000.0)
        self.xSpin.setDecimals(2)
        self.xSpin.setObjectName("xSpin")
        self.positionLayout.addWidget(self.xSpin)
        self.yLabel = QtWidgets.QLabel(Dialog)
        self.yLabel.setObjectName("yLabel")
        self.positionLayout.addWidget(self.yLabel)
        self.ySpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.ySpin.setMinimum(-10000.0)
        self.ySpin.setMaximum(10000.0)
        self.ySpin.setDecimals(2)
        self.ySpin.setObjectName("ySpin")
        self.positionLayout.addWidget(self.ySpin)
        self.zLabel = QtWidgets.QLabel(Dialog)
        self.zLabel.setObjectName("zLabel")
        self.positionLayout.addWidget(self.zLabel)
        self.zSpin = QtWidgets.QDoubleSpinBox(Dialog)
        self.zSpin.setMinimum(-10000.0)
        self.zSpin.setMaximum(10000.0)
        self.zSpin.setDecimals(2)
        self.zSpin.setObjectName("zSpin")
        self.positionLayout.addWidget(self.zSpin)
        self.mainLayout.addLayout(self.positionLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.buttonLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        self.okButton.clicked.connect(Dialog.accept) # type: ignore
        self.cancelButton.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Door Hook Properties"))
        self.roomLabel.setText(_translate("Dialog", "Room:"))
        self.doorLabel.setText(_translate("Dialog", "Door:"))
        self.positionLabel.setText(_translate("Dialog", "Position:"))
        self.xLabel.setText(_translate("Dialog", "X:"))
        self.yLabel.setText(_translate("Dialog", "Y:"))
        self.zLabel.setText(_translate("Dialog", "Z:"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
