# Form implementation generated from reading ui file '..\ui\dialogs\env_variable.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 350)
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setContentsMargins(9, 9, 9, 9)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.nameLayout = QtWidgets.QHBoxLayout()
        self.nameLayout.setSpacing(6)
        self.nameLayout.setObjectName("nameLayout")
        self.nameLabel = QtWidgets.QLabel(parent=Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLayout.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QComboBox(parent=Dialog)
        self.nameEdit.setEditable(True)
        self.nameEdit.setObjectName("nameEdit")
        self.nameLayout.addWidget(self.nameEdit)
        self.mainLayout.addLayout(self.nameLayout)
        self.valueLayout = QtWidgets.QHBoxLayout()
        self.valueLayout.setSpacing(6)
        self.valueLayout.setObjectName("valueLayout")
        self.valueLabel = QtWidgets.QLabel(parent=Dialog)
        self.valueLabel.setObjectName("valueLabel")
        self.valueLayout.addWidget(self.valueLabel)
        self.valueEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.valueEdit.setObjectName("valueEdit")
        self.valueLayout.addWidget(self.valueEdit)
        self.mainLayout.addLayout(self.valueLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setSpacing(6)
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.browseDirButton = QtWidgets.QPushButton(parent=Dialog)
        self.browseDirButton.setObjectName("browseDirButton")
        self.buttonsLayout.addWidget(self.browseDirButton)
        self.browseFileButton = QtWidgets.QPushButton(parent=Dialog)
        self.browseFileButton.setObjectName("browseFileButton")
        self.buttonsLayout.addWidget(self.browseFileButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(parent=Dialog)
        self.okButton.setObjectName("okButton")
        self.buttonsLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.mainLayout.addLayout(self.buttonsLayout)
        self.docsLayout = QtWidgets.QVBoxLayout()
        self.docsLayout.setSpacing(6)
        self.docsLayout.setObjectName("docsLayout")
        self.docLinkLabel = QtWidgets.QLabel(parent=Dialog)
        self.docLinkLabel.setText("")
        self.docLinkLabel.setOpenExternalLinks(True)
        self.docLinkLabel.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.docLinkLabel.setObjectName("docLinkLabel")
        self.docsLayout.addWidget(self.docLinkLabel)
        self.descriptionEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.descriptionEdit.setReadOnly(True)
        self.descriptionEdit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.docsLayout.addWidget(self.descriptionEdit)
        self.mainLayout.addLayout(self.docsLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Edit Qt Environment Variable"))
        self.nameLabel.setText(_translate("Dialog", "Variable name:"))
        self.valueLabel.setText(_translate("Dialog", "Variable value:"))
        self.browseDirButton.setText(_translate("Dialog", "Browse Directory..."))
        self.browseFileButton.setText(_translate("Dialog", "Browse File..."))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.descriptionEdit.setStyleSheet(_translate("Dialog", "background-color: transparent;"))
