# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\find_replace.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        Dialog.setMinimumSize(QtCore.QSize(400, 0))
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.findLayout = QtWidgets.QHBoxLayout()
        self.findLayout.setObjectName("findLayout")
        self.findLabel = QtWidgets.QLabel(Dialog)
        self.findLabel.setObjectName("findLabel")
        self.findLayout.addWidget(self.findLabel)
        self.findEdit = QtWidgets.QLineEdit(Dialog)
        self.findEdit.setObjectName("findEdit")
        self.findLayout.addWidget(self.findEdit)
        self.mainLayout.addLayout(self.findLayout)
        self.replaceLayout = QtWidgets.QHBoxLayout()
        self.replaceLayout.setObjectName("replaceLayout")
        self.replaceLabel = QtWidgets.QLabel(Dialog)
        self.replaceLabel.setObjectName("replaceLabel")
        self.replaceLayout.addWidget(self.replaceLabel)
        self.replaceEdit = QtWidgets.QLineEdit(Dialog)
        self.replaceEdit.setObjectName("replaceEdit")
        self.replaceLayout.addWidget(self.replaceEdit)
        self.mainLayout.addLayout(self.replaceLayout)
        self.optionsLayout = QtWidgets.QHBoxLayout()
        self.optionsLayout.setObjectName("optionsLayout")
        self.caseSensitive = QtWidgets.QCheckBox(Dialog)
        self.caseSensitive.setObjectName("caseSensitive")
        self.optionsLayout.addWidget(self.caseSensitive)
        self.wholeWords = QtWidgets.QCheckBox(Dialog)
        self.wholeWords.setObjectName("wholeWords")
        self.optionsLayout.addWidget(self.wholeWords)
        self.regex = QtWidgets.QCheckBox(Dialog)
        self.regex.setObjectName("regex")
        self.optionsLayout.addWidget(self.regex)
        self.mainLayout.addLayout(self.optionsLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.findButton = QtWidgets.QPushButton(Dialog)
        self.findButton.setObjectName("findButton")
        self.buttonLayout.addWidget(self.findButton)
        self.replaceButton = QtWidgets.QPushButton(Dialog)
        self.replaceButton.setObjectName("replaceButton")
        self.buttonLayout.addWidget(self.replaceButton)
        self.replaceAllButton = QtWidgets.QPushButton(Dialog)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.buttonLayout.addWidget(self.replaceAllButton)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Find and Replace"))
        self.findLabel.setText(_translate("Dialog", "Find:"))
        self.replaceLabel.setText(_translate("Dialog", "Replace:"))
        self.caseSensitive.setText(_translate("Dialog", "Case sensitive"))
        self.wholeWords.setText(_translate("Dialog", "Whole words"))
        self.regex.setText(_translate("Dialog", "Regular expression"))
        self.findButton.setText(_translate("Dialog", "Find"))
        self.replaceButton.setText(_translate("Dialog", "Replace"))
        self.replaceAllButton.setText(_translate("Dialog", "Replace All"))
