# Form implementation generated from reading ui file '..\ui\dialogs\github_selector.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        Dialog.setMinimumSize(QtCore.QSize(600, 400))
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setObjectName("mainLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.mainLayout.addWidget(self.label)
        self.forkLabel = QtWidgets.QLabel(parent=Dialog)
        self.forkLabel.setObjectName("forkLabel")
        self.mainLayout.addWidget(self.forkLabel)
        self.forkComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.forkComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.forkComboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.forkComboBox.setObjectName("forkComboBox")
        self.mainLayout.addWidget(self.forkComboBox)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.filterEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.filterEdit.setObjectName("filterEdit")
        self.filterLayout.addWidget(self.filterEdit)
        self.searchButton = QtWidgets.QPushButton(parent=Dialog)
        self.searchButton.setObjectName("searchButton")
        self.filterLayout.addWidget(self.searchButton)
        self.refreshButton = QtWidgets.QPushButton(parent=Dialog)
        self.refreshButton.setObjectName("refreshButton")
        self.filterLayout.addWidget(self.refreshButton)
        self.mainLayout.addLayout(self.filterLayout)
        self.repoTreeWidget = QtWidgets.QTreeWidget(parent=Dialog)
        self.repoTreeWidget.setColumnCount(1)
        self.repoTreeWidget.setObjectName("repoTreeWidget")
        self.mainLayout.addWidget(self.repoTreeWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.mainLayout.addWidget(self.buttonBox)
        self.cloneButton = QtWidgets.QPushButton(parent=Dialog)
        self.cloneButton.setObjectName("cloneButton")
        self.mainLayout.addWidget(self.cloneButton)
        self.statusBar = QtWidgets.QStatusBar(parent=Dialog)
        self.statusBar.setObjectName("statusBar")
        self.mainLayout.addWidget(self.statusBar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select a GitHub Repository File"))
        self.label.setText(_translate("Dialog", "Please select the correct script path or enter manually:"))
        self.forkLabel.setText(_translate("Dialog", "Select Fork:"))
        self.filterEdit.setPlaceholderText(_translate("Dialog", "Type to filter paths..."))
        self.searchButton.setText(_translate("Dialog", "Search"))
        self.refreshButton.setText(_translate("Dialog", "Refresh"))
        self.repoTreeWidget.setHeaderLabel(_translate("Dialog", "GitHub Repository"))
        self.repoTreeWidget.headerItem().setText(0, _translate("Dialog", "GitHub Repository"))
        self.cloneButton.setText(_translate("Dialog", "Clone Repository"))
