# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\progress_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 80)
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setObjectName("mainLayout")
        self.statusLabel = QtWidgets.QLabel(Dialog)
        self.statusLabel.setObjectName("statusLabel")
        self.mainLayout.addWidget(self.statusLabel)
        self.bytesLabel = QtWidgets.QLabel(Dialog)
        self.bytesLabel.setText("")
        self.bytesLabel.setObjectName("bytesLabel")
        self.mainLayout.addWidget(self.bytesLabel)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.mainLayout.addWidget(self.progressBar)
        self.timeLabel = QtWidgets.QLabel(Dialog)
        self.timeLabel.setObjectName("timeLabel")
        self.mainLayout.addWidget(self.timeLabel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Operation Progress"))
        self.statusLabel.setText(_translate("Dialog", "Initializing..."))
        self.timeLabel.setText(_translate("Dialog", "Time remaining: --/--"))
