# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\reference_search_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.optionsGroup = QtWidgets.QGroupBox(Dialog)
        self.optionsGroup.setObjectName("optionsGroup")
        self.optionsLayout = QtWidgets.QVBoxLayout(self.optionsGroup)
        self.optionsLayout.setObjectName("optionsLayout")
        self.partialMatchCheck = QtWidgets.QCheckBox(self.optionsGroup)
        self.partialMatchCheck.setObjectName("partialMatchCheck")
        self.optionsLayout.addWidget(self.partialMatchCheck)
        self.caseSensitiveCheck = QtWidgets.QCheckBox(self.optionsGroup)
        self.caseSensitiveCheck.setObjectName("caseSensitiveCheck")
        self.optionsLayout.addWidget(self.caseSensitiveCheck)
        self.verticalLayout.addWidget(self.optionsGroup)
        self.patternGroup = QtWidgets.QGroupBox(Dialog)
        self.patternGroup.setObjectName("patternGroup")
        self.patternLayout = QtWidgets.QVBoxLayout(self.patternGroup)
        self.patternLayout.setObjectName("patternLayout")
        self.patternLabel = QtWidgets.QLabel(self.patternGroup)
        self.patternLabel.setObjectName("patternLabel")
        self.patternLayout.addWidget(self.patternLabel)
        self.filePatternEdit = QtWidgets.QLineEdit(self.patternGroup)
        self.filePatternEdit.setObjectName("filePatternEdit")
        self.patternLayout.addWidget(self.filePatternEdit)
        self.verticalLayout.addWidget(self.patternGroup)
        self.typesGroup = QtWidgets.QGroupBox(Dialog)
        self.typesGroup.setObjectName("typesGroup")
        self.typesLayout = QtWidgets.QVBoxLayout(self.typesGroup)
        self.typesLayout.setObjectName("typesLayout")
        self.typesLabel = QtWidgets.QLabel(self.typesGroup)
        self.typesLabel.setObjectName("typesLabel")
        self.typesLayout.addWidget(self.typesLabel)
        self.fileTypesScrollArea = QtWidgets.QScrollArea(self.typesGroup)
        self.fileTypesScrollArea.setWidgetResizable(True)
        self.fileTypesScrollArea.setObjectName("fileTypesScrollArea")
        self.fileTypesScrollAreaWidgetContents = QtWidgets.QWidget()
        self.fileTypesScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 382, 200))
        self.fileTypesScrollAreaWidgetContents.setObjectName("fileTypesScrollAreaWidgetContents")
        self.fileTypesContainerLayout = QtWidgets.QVBoxLayout(self.fileTypesScrollAreaWidgetContents)
        self.fileTypesContainerLayout.setObjectName("fileTypesContainerLayout")
        self.fileTypesScrollArea.setWidget(self.fileTypesScrollAreaWidgetContents)
        self.typesLayout.addWidget(self.fileTypesScrollArea)
        self.verticalLayout.addWidget(self.typesGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reference Search Options"))
        self.optionsGroup.setTitle(_translate("Dialog", "Search Options"))
        self.partialMatchCheck.setText(_translate("Dialog", "Partial match"))
        self.partialMatchCheck.setToolTip(_translate("Dialog", "Allow partial matches (e.g., \'test\' matches \'testscript\')"))
        self.caseSensitiveCheck.setText(_translate("Dialog", "Case sensitive"))
        self.caseSensitiveCheck.setToolTip(_translate("Dialog", "Perform case-sensitive matching"))
        self.patternGroup.setTitle(_translate("Dialog", "File Pattern (optional)"))
        self.patternLabel.setText(_translate("Dialog", "Filter results by filename pattern (e.g., *.mod, *_s.rim):"))
        self.filePatternEdit.setPlaceholderText(_translate("Dialog", "Leave empty to search all files"))
        self.typesGroup.setTitle(_translate("Dialog", "File Types"))
        self.typesLabel.setText(_translate("Dialog", "Select file types to search (leave all checked to search all supported types):"))
