# Form implementation generated from reading ui file '..\ui\dialogs\resource_comparison.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.leftHeader = QtWidgets.QVBoxLayout()
        self.leftHeader.setObjectName("leftHeader")
        self.leftLabel = QtWidgets.QLabel(parent=Dialog)
        self.leftLabel.setObjectName("leftLabel")
        self.leftHeader.addWidget(self.leftLabel)
        self.leftPathLabel = QtWidgets.QLabel(parent=Dialog)
        self.leftPathLabel.setWordWrap(True)
        self.leftPathLabel.setObjectName("leftPathLabel")
        self.leftHeader.addWidget(self.leftPathLabel)
        self.headerLayout.addLayout(self.leftHeader)
        self.rightHeader = QtWidgets.QVBoxLayout()
        self.rightHeader.setObjectName("rightHeader")
        self.rightLabel = QtWidgets.QLabel(parent=Dialog)
        self.rightLabel.setObjectName("rightLabel")
        self.rightHeader.addWidget(self.rightLabel)
        self.rightPathLabel = QtWidgets.QLabel(parent=Dialog)
        self.rightPathLabel.setWordWrap(True)
        self.rightPathLabel.setObjectName("rightPathLabel")
        self.rightHeader.addWidget(self.rightPathLabel)
        self.headerLayout.addLayout(self.rightHeader)
        self.verticalLayout.addLayout(self.headerLayout)
        self.splitter = QtWidgets.QSplitter(parent=Dialog)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.leftText = QtWidgets.QPlainTextEdit(parent=self.splitter)
        self.leftText.setReadOnly(True)
        self.leftText.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.leftText.setObjectName("leftText")
        self.rightText = QtWidgets.QPlainTextEdit(parent=self.splitter)
        self.rightText.setReadOnly(True)
        self.rightText.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.rightText.setObjectName("rightText")
        self.verticalLayout.addWidget(self.splitter)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(parent=Dialog)
        self.closeButton.setObjectName("closeButton")
        self.buttonLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Compare Resources"))
        self.leftLabel.setText(_translate("Dialog", "<b>Left:</b>"))
        self.rightLabel.setText(_translate("Dialog", "<b>Right:</b>"))
        self.closeButton.setText(_translate("Dialog", "Close"))
