# Form implementation generated from reading ui file '..\ui\dialogs\theme_selector.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 650)
        Dialog.setMinimumSize(QtCore.QSize(450, 500))
        self.mainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.mainLayout.setContentsMargins(15, 15, 15, 15)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.searchLayout = QtWidgets.QVBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.searchLabel = QtWidgets.QLabel(parent=Dialog)
        self.searchLabel.setObjectName("searchLabel")
        self.searchLayout.addWidget(self.searchLabel)
        self.searchEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.searchEdit.setObjectName("searchEdit")
        self.searchLayout.addWidget(self.searchEdit)
        self.mainLayout.addLayout(self.searchLayout)
        self.themesLayout = QtWidgets.QVBoxLayout()
        self.themesLayout.setSpacing(5)
        self.themesLayout.setObjectName("themesLayout")
        self.themesHeaderLayout = QtWidgets.QHBoxLayout()
        self.themesHeaderLayout.setObjectName("themesHeaderLayout")
        self.themesLabel = QtWidgets.QLabel(parent=Dialog)
        self.themesLabel.setStyleSheet("font-weight: bold; font-size: 12pt; margin-top: 5px;")
        self.themesLabel.setObjectName("themesLabel")
        self.themesHeaderLayout.addWidget(self.themesLabel)
        self.currentThemeDisplay = QtWidgets.QLineEdit(parent=Dialog)
        self.currentThemeDisplay.setReadOnly(True)
        self.currentThemeDisplay.setStyleSheet("background-color: palette(base); border: 1px solid palette(mid); padding: 2px;")
        self.currentThemeDisplay.setObjectName("currentThemeDisplay")
        self.themesHeaderLayout.addWidget(self.currentThemeDisplay)
        self.themesLayout.addLayout(self.themesHeaderLayout)
        self.themesList = QtWidgets.QListWidget(parent=Dialog)
        self.themesList.setMinimumHeight(200)
        self.themesList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.themesList.setObjectName("themesList")
        self.themesLayout.addWidget(self.themesList)
        self.mainLayout.addLayout(self.themesLayout)
        self.stylesLayout = QtWidgets.QVBoxLayout()
        self.stylesLayout.setSpacing(5)
        self.stylesLayout.setObjectName("stylesLayout")
        self.stylesHeaderLayout = QtWidgets.QHBoxLayout()
        self.stylesHeaderLayout.setObjectName("stylesHeaderLayout")
        self.stylesLabel = QtWidgets.QLabel(parent=Dialog)
        self.stylesLabel.setStyleSheet("font-weight: bold; font-size: 12pt; margin-top: 5px;")
        self.stylesLabel.setObjectName("stylesLabel")
        self.stylesHeaderLayout.addWidget(self.stylesLabel)
        self.currentStyleDisplay = QtWidgets.QLineEdit(parent=Dialog)
        self.currentStyleDisplay.setReadOnly(True)
        self.currentStyleDisplay.setStyleSheet("background-color: palette(base); border: 1px solid palette(mid); padding: 2px;")
        self.currentStyleDisplay.setObjectName("currentStyleDisplay")
        self.stylesHeaderLayout.addWidget(self.currentStyleDisplay)
        self.stylesLayout.addLayout(self.stylesHeaderLayout)
        self.stylesList = QtWidgets.QListWidget(parent=Dialog)
        self.stylesList.setMaximumHeight(150)
        self.stylesList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.stylesList.setObjectName("stylesList")
        self.stylesLayout.addWidget(self.stylesList)
        self.mainLayout.addLayout(self.stylesLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.mainLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Theme Selection"))
        self.searchLabel.setText(_translate("Dialog", "Search:"))
        self.searchEdit.setPlaceholderText(_translate("Dialog", "Filter themes and styles..."))
        self.themesLabel.setText(_translate("Dialog", "Themes:"))
        self.currentThemeDisplay.setPlaceholderText(_translate("Dialog", "No theme selected"))
        self.stylesLabel.setText(_translate("Dialog", "Application Styles:"))
        self.currentStyleDisplay.setPlaceholderText(_translate("Dialog", "No style selected"))
