# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\dialogs\walkmesh_track_properties.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.startRoomLabel = QtWidgets.QLabel(Dialog)
        self.startRoomLabel.setObjectName("startRoomLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.startRoomLabel)
        self.startRoomCombo = QtWidgets.QComboBox(Dialog)
        self.startRoomCombo.setObjectName("startRoomCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.startRoomCombo)
        self.endRoomLabel = QtWidgets.QLabel(Dialog)
        self.endRoomLabel.setObjectName("endRoomLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.endRoomLabel)
        self.endRoomCombo = QtWidgets.QComboBox(Dialog)
        self.endRoomCombo.setObjectName("endRoomCombo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.endRoomCombo)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.buttonLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        self.okButton.clicked.connect(Dialog.accept) # type: ignore
        self.cancelButton.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Track Properties"))
        self.startRoomLabel.setText(_translate("Dialog", "Start Room:"))
        self.endRoomLabel.setText(_translate("Dialog", "End Room:"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
