# Form implementation generated from reading ui file '..\ui\dialogs\walkmesh_room_properties.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.modelLabel = QtWidgets.QLabel(parent=Dialog)
        self.modelLabel.setObjectName("modelLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.modelLabel)
        self.modelEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.modelEdit.setObjectName("modelEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.modelEdit)
        self.positionLabel = QtWidgets.QLabel(parent=Dialog)
        self.positionLabel.setObjectName("positionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.positionLabel)
        self.positionLayout = QtWidgets.QHBoxLayout()
        self.positionLayout.setObjectName("positionLayout")
        self.posX = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.posX.setObjectName("posX")
        self.positionLayout.addWidget(self.posX)
        self.posY = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.posY.setObjectName("posY")
        self.positionLayout.addWidget(self.posY)
        self.posZ = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.posZ.setObjectName("posZ")
        self.positionLayout.addWidget(self.posZ)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.positionLayout)
        self.sizeLabel = QtWidgets.QLabel(parent=Dialog)
        self.sizeLabel.setObjectName("sizeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sizeLabel)
        self.sizeLayout = QtWidgets.QHBoxLayout()
        self.sizeLayout.setObjectName("sizeLayout")
        self.sizeX = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.sizeX.setObjectName("sizeX")
        self.sizeLayout.addWidget(self.sizeX)
        self.sizeY = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.sizeY.setObjectName("sizeY")
        self.sizeLayout.addWidget(self.sizeY)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sizeLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(parent=Dialog)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.buttonLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        self.okButton.clicked.connect(Dialog.accept) # type: ignore
        self.cancelButton.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Room Properties"))
        self.modelLabel.setText(_translate("Dialog", "Model:"))
        self.positionLabel.setText(_translate("Dialog", "Position (X, Y, Z):"))
        self.sizeLabel.setText(_translate("Dialog", "Size (Width, Height):"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
