# Form implementation generated from reading ui file '..\ui\dialogs\walkmesh_doorhook_properties.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.roomLabel = QtWidgets.QLabel(parent=Dialog)
        self.roomLabel.setObjectName("roomLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.roomLabel)
        self.roomCombo = QtWidgets.QComboBox(parent=Dialog)
        self.roomCombo.setObjectName("roomCombo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.roomCombo)
        self.positionLabel = QtWidgets.QLabel(parent=Dialog)
        self.positionLabel.setObjectName("positionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.positionLabel)
        self.positionLayout = QtWidgets.QHBoxLayout()
        self.positionLayout.setObjectName("positionLayout")
        self.posX = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.posX.setObjectName("posX")
        self.positionLayout.addWidget(self.posX)
        self.posY = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.posY.setObjectName("posY")
        self.positionLayout.addWidget(self.posY)
        self.posZ = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.posZ.setObjectName("posZ")
        self.positionLayout.addWidget(self.posZ)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.positionLayout)
        self.orientationLabel = QtWidgets.QLabel(parent=Dialog)
        self.orientationLabel.setObjectName("orientationLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.orientationLabel)
        self.orientationSpinBox = QtWidgets.QDoubleSpinBox(parent=Dialog)
        self.orientationSpinBox.setMinimum(0.0)
        self.orientationSpinBox.setMaximum(359.99)
        self.orientationSpinBox.setObjectName("orientationSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.orientationSpinBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(parent=Dialog)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.buttonLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Dialog)
        self.okButton.clicked.connect(Dialog.accept) # type: ignore
        self.cancelButton.clicked.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Door Hook Properties"))
        self.roomLabel.setText(_translate("Dialog", "Room:"))
        self.positionLabel.setText(_translate("Dialog", "Position (X, Y, Z):"))
        self.orientationLabel.setText(_translate("Dialog", "Orientation (degrees):"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
