# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\windows\module_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 651)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbarFrame = QtWidgets.QFrame(self.centralwidget)
        self.toolbarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolbarFrame.setObjectName("toolbarFrame")
        self.toolbarFrameLayout = QtWidgets.QVBoxLayout(self.toolbarFrame)
        self.toolbarFrameLayout.setContentsMargins(8, 6, 8, 6)
        self.toolbarFrameLayout.setSpacing(6)
        self.toolbarFrameLayout.setObjectName("toolbarFrameLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.modeLabelWidget = QtWidgets.QLabel(self.toolbarFrame)
        self.modeLabelWidget.setMaximumSize(QtCore.QSize(40, 16777215))
        self.modeLabelWidget.setObjectName("modeLabelWidget")
        self.horizontalLayout_2.addWidget(self.modeLabelWidget)
        self.modeSelector = QtWidgets.QComboBox(self.toolbarFrame)
        self.modeSelector.setMaximumSize(QtCore.QSize(130, 16777215))
        self.modeSelector.setObjectName("modeSelector")
        self.modeSelector.addItem("")
        self.modeSelector.addItem("")
        self.modeSelector.addItem("")
        self.horizontalLayout_2.addWidget(self.modeSelector)
        self.modeSeparator = QtWidgets.QFrame(self.toolbarFrame)
        self.modeSeparator.setFrameShape(QtWidgets.QFrame.VLine)
        self.modeSeparator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.modeSeparator.setObjectName("modeSeparator")
        self.horizontalLayout_2.addWidget(self.modeSeparator)
        self.toolSelectBtn = QtWidgets.QPushButton(self.toolbarFrame)
        self.toolSelectBtn.setCheckable(True)
        self.toolSelectBtn.setChecked(True)
        self.toolSelectBtn.setMaximumSize(QtCore.QSize(90, 16777215))
        self.toolSelectBtn.setObjectName("toolSelectBtn")
        self.horizontalLayout_2.addWidget(self.toolSelectBtn)
        self.toolMoveBtn = QtWidgets.QPushButton(self.toolbarFrame)
        self.toolMoveBtn.setCheckable(True)
        self.toolMoveBtn.setMaximumSize(QtCore.QSize(90, 16777215))
        self.toolMoveBtn.setObjectName("toolMoveBtn")
        self.horizontalLayout_2.addWidget(self.toolMoveBtn)
        self.toolRotateBtn = QtWidgets.QPushButton(self.toolbarFrame)
        self.toolRotateBtn.setCheckable(True)
        self.toolRotateBtn.setMaximumSize(QtCore.QSize(90, 16777215))
        self.toolRotateBtn.setObjectName("toolRotateBtn")
        self.horizontalLayout_2.addWidget(self.toolRotateBtn)
        self.toolSeparator = QtWidgets.QFrame(self.toolbarFrame)
        self.toolSeparator.setFrameShape(QtWidgets.QFrame.VLine)
        self.toolSeparator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolSeparator.setObjectName("toolSeparator")
        self.horizontalLayout_2.addWidget(self.toolSeparator)
        self.snapCheck = QtWidgets.QCheckBox(self.toolbarFrame)
        self.snapCheck.setObjectName("snapCheck")
        self.horizontalLayout_2.addWidget(self.snapCheck)
        self.snapSizeSpin = QtWidgets.QDoubleSpinBox(self.toolbarFrame)
        self.snapSizeSpin.setMinimum(0.05)
        self.snapSizeSpin.setMaximum(10.0)
        self.snapSizeSpin.setSingleStep(0.25)
        self.snapSizeSpin.setProperty("value", 0.5)
        self.snapSizeSpin.setMaximumSize(QtCore.QSize(84, 16777215))
        self.snapSizeSpin.setObjectName("snapSizeSpin")
        self.horizontalLayout_2.addWidget(self.snapSizeSpin)
        self.rotSnapCheck = QtWidgets.QCheckBox(self.toolbarFrame)
        self.rotSnapCheck.setObjectName("rotSnapCheck")
        self.horizontalLayout_2.addWidget(self.rotSnapCheck)
        self.rotSnapDegreeSpin = QtWidgets.QDoubleSpinBox(self.toolbarFrame)
        self.rotSnapDegreeSpin.setMinimum(1.0)
        self.rotSnapDegreeSpin.setMaximum(90.0)
        self.rotSnapDegreeSpin.setSingleStep(5.0)
        self.rotSnapDegreeSpin.setProperty("value", 15.0)
        self.rotSnapDegreeSpin.setMaximumSize(QtCore.QSize(74, 16777215))
        self.rotSnapDegreeSpin.setObjectName("rotSnapDegreeSpin")
        self.horizontalLayout_2.addWidget(self.rotSnapDegreeSpin)
        self.snapSeparator = QtWidgets.QFrame(self.toolbarFrame)
        self.snapSeparator.setFrameShape(QtWidgets.QFrame.VLine)
        self.snapSeparator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.snapSeparator.setObjectName("snapSeparator")
        self.horizontalLayout_2.addWidget(self.snapSeparator)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.toolbarFrameLayout.addLayout(self.horizontalLayout_2)
        self.toolbarSecondaryLayout = QtWidgets.QHBoxLayout()
        self.toolbarSecondaryLayout.setSpacing(8)
        self.toolbarSecondaryLayout.setObjectName("toolbarSecondaryLayout")
        self.sceneOptionsFrame = QtWidgets.QFrame(self.toolbarFrame)
        self.sceneOptionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sceneOptionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sceneOptionsFrame.setObjectName("sceneOptionsFrame")
        self.sceneOptionsFrameLayout = QtWidgets.QHBoxLayout(self.sceneOptionsFrame)
        self.sceneOptionsFrameLayout.setContentsMargins(6, 4, 6, 4)
        self.sceneOptionsFrameLayout.setSpacing(4)
        self.sceneOptionsFrameLayout.setObjectName("sceneOptionsFrameLayout")
        self.sceneOptionsLabel = QtWidgets.QLabel(self.sceneOptionsFrame)
        self.sceneOptionsLabel.setObjectName("sceneOptionsLabel")
        self.sceneOptionsFrameLayout.addWidget(self.sceneOptionsLabel)
        self.lockInstancesCheck = QtWidgets.QCheckBox(self.sceneOptionsFrame)
        self.lockInstancesCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.lockInstancesCheck.setStyleSheet("QCheckbox { spacing: 0px; }\n"
"                QCheckBox::indicator {\n"
"                image: url(:/images/icons/lock.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }")
        self.lockInstancesCheck.setText("")
        self.lockInstancesCheck.setChecked(False)
        self.lockInstancesCheck.setObjectName("lockInstancesCheck")
        self.sceneOptionsFrameLayout.addWidget(self.lockInstancesCheck)
        self.cursorCheck = QtWidgets.QCheckBox(self.sceneOptionsFrame)
        self.cursorCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.cursorCheck.setChecked(True)
        self.cursorCheck.setStyleSheet("QCheckbox {\n"
"                spacing: 0px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator {\n"
"                image: url(:/images/icons/cursor.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.cursorCheck.setText("")
        self.cursorCheck.setChecked(True)
        self.cursorCheck.setObjectName("cursorCheck")
        self.sceneOptionsFrameLayout.addWidget(self.cursorCheck)
        self.roomBoundariesCheck = QtWidgets.QCheckBox(self.sceneOptionsFrame)
        self.roomBoundariesCheck.setChecked(True)
        self.roomBoundariesCheck.setObjectName("roomBoundariesCheck")
        self.sceneOptionsFrameLayout.addWidget(self.roomBoundariesCheck)
        self.flatGridCheck = QtWidgets.QCheckBox(self.sceneOptionsFrame)
        self.flatGridCheck.setChecked(False)
        self.flatGridCheck.setObjectName("flatGridCheck")
        self.sceneOptionsFrameLayout.addWidget(self.flatGridCheck)
        self.walkmeshEdgesCheck = QtWidgets.QCheckBox(self.sceneOptionsFrame)
        self.walkmeshEdgesCheck.setChecked(False)
        self.walkmeshEdgesCheck.setObjectName("walkmeshEdgesCheck")
        self.sceneOptionsFrameLayout.addWidget(self.walkmeshEdgesCheck)
        self.toolbarSecondaryLayout.addWidget(self.sceneOptionsFrame)
        self.renderOptionsFrame = QtWidgets.QFrame(self.toolbarFrame)
        self.renderOptionsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.renderOptionsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.renderOptionsFrame.setObjectName("renderOptionsFrame")
        self.renderOptionsFrameLayout = QtWidgets.QHBoxLayout(self.renderOptionsFrame)
        self.renderOptionsFrameLayout.setContentsMargins(6, 4, 6, 4)
        self.renderOptionsFrameLayout.setSpacing(4)
        self.renderOptionsFrameLayout.setObjectName("renderOptionsFrameLayout")
        self.renderOptionsLabel = QtWidgets.QLabel(self.renderOptionsFrame)
        self.renderOptionsLabel.setObjectName("renderOptionsLabel")
        self.renderOptionsFrameLayout.addWidget(self.renderOptionsLabel)
        self.backfaceCheck = QtWidgets.QCheckBox(self.renderOptionsFrame)
        self.backfaceCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.backfaceCheck.setStyleSheet("QCheckbox {\n"
"                spacing: 0px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator {\n"
"                image: url(:/images/icons/backface.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.backfaceCheck.setText("")
        self.backfaceCheck.setChecked(True)
        self.backfaceCheck.setObjectName("backfaceCheck")
        self.renderOptionsFrameLayout.addWidget(self.backfaceCheck)
        self.lightmapCheck = QtWidgets.QCheckBox(self.renderOptionsFrame)
        self.lightmapCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.lightmapCheck.setStyleSheet("QCheckbox {\n"
"                spacing: 0px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator {\n"
"                image: url(:/images/icons/lightmap.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.lightmapCheck.setText("")
        self.lightmapCheck.setChecked(True)
        self.lightmapCheck.setObjectName("lightmapCheck")
        self.renderOptionsFrameLayout.addWidget(self.lightmapCheck)
        self.toolbarSecondaryLayout.addWidget(self.renderOptionsFrame)
        self.visibilityFiltersFrame = QtWidgets.QFrame(self.toolbarFrame)
        self.visibilityFiltersFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.visibilityFiltersFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.visibilityFiltersFrame.setObjectName("visibilityFiltersFrame")
        self.visibilityFiltersFrameLayout = QtWidgets.QHBoxLayout(self.visibilityFiltersFrame)
        self.visibilityFiltersFrameLayout.setContentsMargins(6, 4, 6, 4)
        self.visibilityFiltersFrameLayout.setSpacing(4)
        self.visibilityFiltersFrameLayout.setObjectName("visibilityFiltersFrameLayout")
        self.visibilityFiltersLabel = QtWidgets.QLabel(self.visibilityFiltersFrame)
        self.visibilityFiltersLabel.setObjectName("visibilityFiltersLabel")
        self.visibilityFiltersFrameLayout.addWidget(self.visibilityFiltersLabel)
        self.viewCreatureCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewCreatureCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewCreatureCheck.setStyleSheet("QCheckbox {\n"
"                spacing: 0px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/creature.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewCreatureCheck.setText("")
        self.viewCreatureCheck.setChecked(True)
        self.viewCreatureCheck.setObjectName("viewCreatureCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewCreatureCheck)
        self.viewDoorCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewDoorCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewDoorCheck.setStyleSheet("QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/door.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewDoorCheck.setText("")
        self.viewDoorCheck.setChecked(True)
        self.viewDoorCheck.setObjectName("viewDoorCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewDoorCheck)
        self.viewPlaceableCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewPlaceableCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewPlaceableCheck.setStyleSheet("QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/placeable.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewPlaceableCheck.setText("")
        self.viewPlaceableCheck.setChecked(True)
        self.viewPlaceableCheck.setObjectName("viewPlaceableCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewPlaceableCheck)
        self.viewStoreCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewStoreCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewStoreCheck.setStyleSheet("QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/merchant.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewStoreCheck.setText("")
        self.viewStoreCheck.setChecked(True)
        self.viewStoreCheck.setObjectName("viewStoreCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewStoreCheck)
        self.viewSoundCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewSoundCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewSoundCheck.setStyleSheet("QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/sound.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewSoundCheck.setText("")
        self.viewSoundCheck.setChecked(True)
        self.viewSoundCheck.setObjectName("viewSoundCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewSoundCheck)
        self.viewWaypointCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewWaypointCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewWaypointCheck.setStyleSheet("QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/waypoint.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewWaypointCheck.setText("")
        self.viewWaypointCheck.setChecked(True)
        self.viewWaypointCheck.setObjectName("viewWaypointCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewWaypointCheck)
        self.viewCameraCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewCameraCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewCameraCheck.setStyleSheet("QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/camera.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewCameraCheck.setText("")
        self.viewCameraCheck.setChecked(True)
        self.viewCameraCheck.setObjectName("viewCameraCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewCameraCheck)
        self.viewEncounterCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewEncounterCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewEncounterCheck.setStyleSheet("QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/encounter.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewEncounterCheck.setText("")
        self.viewEncounterCheck.setChecked(True)
        self.viewEncounterCheck.setObjectName("viewEncounterCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewEncounterCheck)
        self.viewTriggerCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.viewTriggerCheck.setMaximumSize(QtCore.QSize(28, 16777215))
        self.viewTriggerCheck.setStyleSheet("QCheckBox::indicator {\n"
"                image: url(:/images/icons/k1/trigger.png);\n"
"                border: 1px solid rgba(30, 144, 255, 0.0);\n"
"                width: 26px;\n"
"                height: 26px;\n"
"                }\n"
"\n"
"                QCheckBox::indicator:unchecked:hover {\n"
"                background: rgba(30, 144, 255, 0.2);\n"
"                border: 1px solid rgba(30, 144, 255, 0.4);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked {\n"
"                background: rgba(30, 144, 255, 0.4);\n"
"                border:1px solid rgba(30, 144, 255, 0.6);\n"
"                }\n"
"\n"
"                QCheckBox::indicator:checked:hover {\n"
"                background: rgba(30, 144, 255, 0.5);\n"
"                border:1px solid rgba(30, 144, 255, 0.7);\n"
"                }\n"
"\n"
"               ")
        self.viewTriggerCheck.setText("")
        self.viewTriggerCheck.setChecked(True)
        self.viewTriggerCheck.setObjectName("viewTriggerCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.viewTriggerCheck)
        self.pickHiddenCheck = QtWidgets.QCheckBox(self.visibilityFiltersFrame)
        self.pickHiddenCheck.setChecked(False)
        self.pickHiddenCheck.setObjectName("pickHiddenCheck")
        self.visibilityFiltersFrameLayout.addWidget(self.pickHiddenCheck)
        self.toolbarSecondaryLayout.addWidget(self.visibilityFiltersFrame)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.toolbarSecondaryLayout.addItem(spacerItem1)
        self.toolbarFrameLayout.addLayout(self.toolbarSecondaryLayout)
        self.verticalLayout.addWidget(self.toolbarFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPanel = QtWidgets.QTabWidget(self.centralwidget)
        self.leftPanel.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftPanel.setObjectName("leftPanel")
        self.resourceTab = QtWidgets.QWidget()
        self.resourceTab.setObjectName("resourceTab")
        self.resourceTabLayout = QtWidgets.QVBoxLayout(self.resourceTab)
        self.resourceTabLayout.setObjectName("resourceTabLayout")
        self.resourceSearchEdit = QtWidgets.QLineEdit(self.resourceTab)
        self.resourceSearchEdit.setClearButtonEnabled(True)
        self.resourceSearchEdit.setObjectName("resourceSearchEdit")
        self.resourceTabLayout.addWidget(self.resourceSearchEdit)
        self.resourceTree = QtWidgets.QTreeWidget(self.resourceTab)
        self.resourceTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.resourceTree.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resourceTree.setHeaderHidden(True)
        self.resourceTree.setObjectName("resourceTree")
        self.resourceTree.headerItem().setText(0, "1")
        self.resourceTabLayout.addWidget(self.resourceTree)
        self.leftPanel.addTab(self.resourceTab, "")
        self.lytTab = QtWidgets.QWidget()
        self.lytTab.setObjectName("lytTab")
        self.lytTabLayout = QtWidgets.QVBoxLayout(self.lytTab)
        self.lytTabLayout.setObjectName("lytTabLayout")
        self.lytToolbar = QtWidgets.QToolBar(self.lytTab)
        self.lytToolbar.setObjectName("lytToolbar")
        self.lytTabLayout.addWidget(self.lytToolbar)
        self.lytSplitter = QtWidgets.QSplitter(self.lytTab)
        self.lytSplitter.setOrientation(QtCore.Qt.Vertical)
        self.lytSplitter.setObjectName("lytSplitter")
        self.lytTree = QtWidgets.QTreeWidget(self.lytSplitter)
        self.lytTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lytTree.setHeaderHidden(True)
        self.lytTree.setObjectName("lytTree")
        self.lytElementTabs = QtWidgets.QTabWidget(self.lytSplitter)
        self.lytElementTabs.setObjectName("lytElementTabs")
        self.roomTab = QtWidgets.QWidget()
        self.roomTab.setObjectName("roomTab")
        self.roomLayout = QtWidgets.QFormLayout(self.roomTab)
        self.roomLayout.setObjectName("roomLayout")
        self.modelLabel = QtWidgets.QLabel(self.roomTab)
        self.modelLabel.setObjectName("modelLabel")
        self.roomLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.modelLabel)
        self.modelLayout = QtWidgets.QHBoxLayout()
        self.modelLayout.setObjectName("modelLayout")
        self.modelEdit = QtWidgets.QLineEdit(self.roomTab)
        self.modelEdit.setObjectName("modelEdit")
        self.modelLayout.addWidget(self.modelEdit)
        self.browseModelButton = QtWidgets.QToolButton(self.roomTab)
        self.browseModelButton.setObjectName("browseModelButton")
        self.modelLayout.addWidget(self.browseModelButton)
        self.roomLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.modelLayout)
        self.positionLabel = QtWidgets.QLabel(self.roomTab)
        self.positionLabel.setObjectName("positionLabel")
        self.roomLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.positionLabel)
        self.positionLayout = QtWidgets.QHBoxLayout()
        self.positionLayout.setObjectName("positionLayout")
        self.posXSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.posXSpin.setDecimals(3)
        self.posXSpin.setMinimum(-10000.0)
        self.posXSpin.setMaximum(10000.0)
        self.posXSpin.setObjectName("posXSpin")
        self.positionLayout.addWidget(self.posXSpin)
        self.posYSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.posYSpin.setDecimals(3)
        self.posYSpin.setMinimum(-10000.0)
        self.posYSpin.setMaximum(10000.0)
        self.posYSpin.setObjectName("posYSpin")
        self.positionLayout.addWidget(self.posYSpin)
        self.posZSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.posZSpin.setDecimals(3)
        self.posZSpin.setMinimum(-10000.0)
        self.posZSpin.setMaximum(10000.0)
        self.posZSpin.setObjectName("posZSpin")
        self.positionLayout.addWidget(self.posZSpin)
        self.roomLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.positionLayout)
        self.rotationLabel = QtWidgets.QLabel(self.roomTab)
        self.rotationLabel.setObjectName("rotationLabel")
        self.roomLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rotationLabel)
        self.rotationLayout = QtWidgets.QHBoxLayout()
        self.rotationLayout.setObjectName("rotationLayout")
        self.rotXSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.rotXSpin.setDecimals(3)
        self.rotXSpin.setMinimum(-360.0)
        self.rotXSpin.setMaximum(360.0)
        self.rotXSpin.setObjectName("rotXSpin")
        self.rotationLayout.addWidget(self.rotXSpin)
        self.rotYSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.rotYSpin.setDecimals(3)
        self.rotYSpin.setMinimum(-360.0)
        self.rotYSpin.setMaximum(360.0)
        self.rotYSpin.setObjectName("rotYSpin")
        self.rotationLayout.addWidget(self.rotYSpin)
        self.rotZSpin = QtWidgets.QDoubleSpinBox(self.roomTab)
        self.rotZSpin.setDecimals(3)
        self.rotZSpin.setMinimum(-360.0)
        self.rotZSpin.setMaximum(360.0)
        self.rotZSpin.setObjectName("rotZSpin")
        self.rotationLayout.addWidget(self.rotZSpin)
        self.roomLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.rotationLayout)
        self.lytElementTabs.addTab(self.roomTab, "")
        self.doorHookTab = QtWidgets.QWidget()
        self.doorHookTab.setObjectName("doorHookTab")
        self.doorHookLayout = QtWidgets.QFormLayout(self.doorHookTab)
        self.doorHookLayout.setObjectName("doorHookLayout")
        self.roomNameLabel = QtWidgets.QLabel(self.doorHookTab)
        self.roomNameLabel.setObjectName("roomNameLabel")
        self.doorHookLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.roomNameLabel)
        self.roomNameCombo = QtWidgets.QComboBox(self.doorHookTab)
        self.roomNameCombo.setObjectName("roomNameCombo")
        self.doorHookLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.roomNameCombo)
        self.doorNameLabel = QtWidgets.QLabel(self.doorHookTab)
        self.doorNameLabel.setObjectName("doorNameLabel")
        self.doorHookLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.doorNameLabel)
        self.doorNameEdit = QtWidgets.QLineEdit(self.doorHookTab)
        self.doorNameEdit.setObjectName("doorNameEdit")
        self.doorHookLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doorNameEdit)
        self.lytElementTabs.addTab(self.doorHookTab, "")
        self.lytTabLayout.addWidget(self.lytSplitter)
        self.leftPanel.addTab(self.lytTab, "")
        self.walkmeshTab = QtWidgets.QWidget()
        self.walkmeshTab.setObjectName("walkmeshTab")
        self.walkmeshTabLayout = QtWidgets.QVBoxLayout(self.walkmeshTab)
        self.walkmeshTabLayout.setContentsMargins(2, 2, 2, 2)
        self.walkmeshTabLayout.setSpacing(4)
        self.walkmeshTabLayout.setObjectName("walkmeshTabLayout")
        self.walkmeshPainterBox = QtWidgets.QGroupBox(self.walkmeshTab)
        self.walkmeshPainterBox.setObjectName("walkmeshPainterBox")
        self.walkmeshPainterLayout = QtWidgets.QVBoxLayout(self.walkmeshPainterBox)
        self.walkmeshPainterLayout.setSpacing(4)
        self.walkmeshPainterLayout.setObjectName("walkmeshPainterLayout")
        self.enablePaintCheck = QtWidgets.QCheckBox(self.walkmeshPainterBox)
        self.enablePaintCheck.setObjectName("enablePaintCheck")
        self.walkmeshPainterLayout.addWidget(self.enablePaintCheck)
        self.colorizeMaterialsCheck = QtWidgets.QCheckBox(self.walkmeshPainterBox)
        self.colorizeMaterialsCheck.setChecked(True)
        self.colorizeMaterialsCheck.setObjectName("colorizeMaterialsCheck")
        self.walkmeshPainterLayout.addWidget(self.colorizeMaterialsCheck)
        self.materialList = QtWidgets.QListWidget(self.walkmeshPainterBox)
        self.materialList.setMinimumHeight(150)
        self.materialList.setObjectName("materialList")
        self.walkmeshPainterLayout.addWidget(self.materialList)
        self.walkmeshButtonsLayout = QtWidgets.QHBoxLayout()
        self.walkmeshButtonsLayout.setObjectName("walkmeshButtonsLayout")
        self.resetPaintButton = QtWidgets.QPushButton(self.walkmeshPainterBox)
        self.resetPaintButton.setObjectName("resetPaintButton")
        self.walkmeshButtonsLayout.addWidget(self.resetPaintButton)
        self.walkmeshPainterLayout.addLayout(self.walkmeshButtonsLayout)
        self.walkmeshTabLayout.addWidget(self.walkmeshPainterBox)
        self.walkmeshFacePropsBox = QtWidgets.QGroupBox(self.walkmeshTab)
        self.walkmeshFacePropsBox.setObjectName("walkmeshFacePropsBox")
        self.walkmeshFaceLayout = QtWidgets.QFormLayout(self.walkmeshFacePropsBox)
        self.walkmeshFaceLayout.setObjectName("walkmeshFaceLayout")
        self.faceMaterialLabel = QtWidgets.QLabel(self.walkmeshFacePropsBox)
        self.faceMaterialLabel.setObjectName("faceMaterialLabel")
        self.walkmeshFaceLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.faceMaterialLabel)
        self.faceMaterialCombo = QtWidgets.QComboBox(self.walkmeshFacePropsBox)
        self.faceMaterialCombo.setObjectName("faceMaterialCombo")
        self.walkmeshFaceLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.faceMaterialCombo)
        self.faceWalkLabel = QtWidgets.QLabel(self.walkmeshFacePropsBox)
        self.faceWalkLabel.setObjectName("faceWalkLabel")
        self.walkmeshFaceLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.faceWalkLabel)
        self.faceWalkCheck = QtWidgets.QCheckBox(self.walkmeshFacePropsBox)
        self.faceWalkCheck.setText("")
        self.faceWalkCheck.setObjectName("faceWalkCheck")
        self.walkmeshFaceLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.faceWalkCheck)
        self.faceWalkCheckLabel = QtWidgets.QLabel(self.walkmeshFacePropsBox)
        self.faceWalkCheckLabel.setObjectName("faceWalkCheckLabel")
        self.walkmeshFaceLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.faceWalkCheckLabel)
        self.faceWalkCheckCheck = QtWidgets.QCheckBox(self.walkmeshFacePropsBox)
        self.faceWalkCheckCheck.setText("")
        self.faceWalkCheckCheck.setObjectName("faceWalkCheckCheck")
        self.walkmeshFaceLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.faceWalkCheckCheck)
        self.faceLosLabel = QtWidgets.QLabel(self.walkmeshFacePropsBox)
        self.faceLosLabel.setObjectName("faceLosLabel")
        self.walkmeshFaceLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.faceLosLabel)
        self.faceLosCheck = QtWidgets.QCheckBox(self.walkmeshFacePropsBox)
        self.faceLosCheck.setText("")
        self.faceLosCheck.setObjectName("faceLosCheck")
        self.walkmeshFaceLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.faceLosCheck)
        self.walkmeshTabLayout.addWidget(self.walkmeshFacePropsBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.walkmeshTabLayout.addItem(spacerItem2)
        self.leftPanel.addTab(self.walkmeshTab, "")
        self.visTab = QtWidgets.QWidget()
        self.visTab.setObjectName("visTab")
        self.visTabLayout = QtWidgets.QVBoxLayout(self.visTab)
        self.visTabLayout.setContentsMargins(2, 2, 2, 2)
        self.visTabLayout.setSpacing(4)
        self.visTabLayout.setObjectName("visTabLayout")
        self.visInfoLabel = QtWidgets.QLabel(self.visTab)
        self.visInfoLabel.setWordWrap(True)
        self.visInfoLabel.setObjectName("visInfoLabel")
        self.visTabLayout.addWidget(self.visInfoLabel)
        self.visMatrix = QtWidgets.QTreeWidget(self.visTab)
        self.visMatrix.setHeaderHidden(False)
        self.visMatrix.setObjectName("visMatrix")
        self.visTabLayout.addWidget(self.visMatrix)
        self.visButtonsLayout = QtWidgets.QHBoxLayout()
        self.visButtonsLayout.setObjectName("visButtonsLayout")
        self.visSetAllButton = QtWidgets.QPushButton(self.visTab)
        self.visSetAllButton.setObjectName("visSetAllButton")
        self.visButtonsLayout.addWidget(self.visSetAllButton)
        self.visClearAllButton = QtWidgets.QPushButton(self.visTab)
        self.visClearAllButton.setObjectName("visClearAllButton")
        self.visButtonsLayout.addWidget(self.visClearAllButton)
        self.visTabLayout.addLayout(self.visButtonsLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.visTabLayout.addItem(spacerItem3)
        self.leftPanel.addTab(self.visTab, "")
        self.horizontalLayout.addWidget(self.leftPanel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.mainRenderer = ModuleRenderer(self.splitter)
        self.mainRenderer.setMouseTracking(True)
        self.mainRenderer.setObjectName("mainRenderer")
        self.flatRenderer = WalkmeshRenderer(self.splitter)
        self.flatRenderer.setMouseTracking(True)
        self.flatRenderer.setObjectName("flatRenderer")
        self.indoorRenderer = IndoorMapRenderer(self.splitter)
        self.indoorRenderer.setMouseTracking(True)
        self.indoorRenderer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.indoorRenderer.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.indoorRenderer.setVisible(False)
        self.indoorRenderer.setObjectName("indoorRenderer")
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.rightPanel = QtWidgets.QTabWidget(self.centralwidget)
        self.rightPanel.setMaximumSize(QtCore.QSize(250, 16777215))
        self.rightPanel.setObjectName("rightPanel")
        self.instancesTab = QtWidgets.QWidget()
        self.instancesTab.setObjectName("instancesTab")
        self.instancePanelLayout = QtWidgets.QVBoxLayout(self.instancesTab)
        self.instancePanelLayout.setContentsMargins(0, 0, 0, 0)
        self.instancePanelLayout.setObjectName("instancePanelLayout")
        self.instanceSearchEdit = QtWidgets.QLineEdit(self.instancesTab)
        self.instanceSearchEdit.setClearButtonEnabled(True)
        self.instanceSearchEdit.setObjectName("instanceSearchEdit")
        self.instancePanelLayout.addWidget(self.instanceSearchEdit)
        self.instanceTree = QtWidgets.QTreeWidget(self.instancesTab)
        self.instanceTree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.instanceTree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.instanceTree.setHeaderHidden(True)
        self.instanceTree.setObjectName("instanceTree")
        self.instanceTree.headerItem().setText(0, "1")
        self.instancePanelLayout.addWidget(self.instanceTree)
        self.propertiesGroup = QtWidgets.QGroupBox(self.instancesTab)
        self.propertiesGroup.setObjectName("propertiesGroup")
        self.propertiesLayout = QtWidgets.QFormLayout(self.propertiesGroup)
        self.propertiesLayout.setObjectName("propertiesLayout")
        self.propResRefLabel = QtWidgets.QLabel(self.propertiesGroup)
        self.propResRefLabel.setObjectName("propResRefLabel")
        self.propertiesLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.propResRefLabel)
        self.propResRefValue = QtWidgets.QLabel(self.propertiesGroup)
        self.propResRefValue.setObjectName("propResRefValue")
        self.propertiesLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.propResRefValue)
        self.propTypeLabel = QtWidgets.QLabel(self.propertiesGroup)
        self.propTypeLabel.setObjectName("propTypeLabel")
        self.propertiesLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.propTypeLabel)
        self.propTypeValue = QtWidgets.QLabel(self.propertiesGroup)
        self.propTypeValue.setObjectName("propTypeValue")
        self.propertiesLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.propTypeValue)
        self.label = QtWidgets.QLabel(self.propertiesGroup)
        self.label.setObjectName("label")
        self.propertiesLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.propXSpin = QtWidgets.QDoubleSpinBox(self.propertiesGroup)
        self.propXSpin.setMinimum(-9999.0)
        self.propXSpin.setMaximum(9999.0)
        self.propXSpin.setSingleStep(0.1)
        self.propXSpin.setDecimals(3)
        self.propXSpin.setObjectName("propXSpin")
        self.propertiesLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.propXSpin)
        self.label1 = QtWidgets.QLabel(self.propertiesGroup)
        self.label1.setObjectName("label1")
        self.propertiesLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.propYSpin = QtWidgets.QDoubleSpinBox(self.propertiesGroup)
        self.propYSpin.setMinimum(-9999.0)
        self.propYSpin.setMaximum(9999.0)
        self.propYSpin.setSingleStep(0.1)
        self.propYSpin.setDecimals(3)
        self.propYSpin.setObjectName("propYSpin")
        self.propertiesLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.propYSpin)
        self.label2 = QtWidgets.QLabel(self.propertiesGroup)
        self.label2.setObjectName("label2")
        self.propertiesLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.propZSpin = QtWidgets.QDoubleSpinBox(self.propertiesGroup)
        self.propZSpin.setMinimum(-9999.0)
        self.propZSpin.setMaximum(9999.0)
        self.propZSpin.setSingleStep(0.1)
        self.propZSpin.setDecimals(3)
        self.propZSpin.setObjectName("propZSpin")
        self.propertiesLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.propZSpin)
        self.label3 = QtWidgets.QLabel(self.propertiesGroup)
        self.label3.setObjectName("label3")
        self.propertiesLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label3)
        self.propBearingSpin = QtWidgets.QDoubleSpinBox(self.propertiesGroup)
        self.propBearingSpin.setMinimum(-360.0)
        self.propBearingSpin.setMaximum(360.0)
        self.propBearingSpin.setSingleStep(1.0)
        self.propBearingSpin.setDecimals(1)
        self.propBearingSpin.setObjectName("propBearingSpin")
        self.propertiesLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.propBearingSpin)
        self.propOpenBlueprintBtn = QtWidgets.QPushButton(self.propertiesGroup)
        self.propOpenBlueprintBtn.setObjectName("propOpenBlueprintBtn")
        self.propertiesLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.propOpenBlueprintBtn)
        self.instancePanelLayout.addWidget(self.propertiesGroup)
        self.rightPanel.addTab(self.instancesTab, "")
        self.layoutTab = QtWidgets.QWidget()
        self.layoutTab.setObjectName("layoutTab")
        self.layoutTabLayout = QtWidgets.QVBoxLayout(self.layoutTab)
        self.layoutTabLayout.setContentsMargins(2, 2, 2, 2)
        self.layoutTabLayout.setSpacing(4)
        self.layoutTabLayout.setObjectName("layoutTabLayout")
        self.indoorPreviewBox = QtWidgets.QGroupBox(self.layoutTab)
        self.indoorPreviewBox.setObjectName("indoorPreviewBox")
        self.indoorPreviewLayout = QtWidgets.QGridLayout(self.indoorPreviewBox)
        self.indoorPreviewLayout.setObjectName("indoorPreviewLayout")
        self.indoorPreviewImage = QtWidgets.QLabel(self.indoorPreviewBox)
        self.indoorPreviewImage.setText("")
        self.indoorPreviewImage.setScaledContents(True)
        self.indoorPreviewImage.setMinimumSize(QtCore.QSize(100, 100))
        self.indoorPreviewImage.setObjectName("indoorPreviewImage")
        self.indoorPreviewLayout.addWidget(self.indoorPreviewImage, 0, 0, 1, 1)
        self.layoutTabLayout.addWidget(self.indoorPreviewBox)
        self.indoorKitsGroupBox = QtWidgets.QGroupBox(self.layoutTab)
        self.indoorKitsGroupBox.setObjectName("indoorKitsGroupBox")
        self.indoorKitsLayout = QtWidgets.QVBoxLayout(self.indoorKitsGroupBox)
        self.indoorKitsLayout.setSpacing(4)
        self.indoorKitsLayout.setObjectName("indoorKitsLayout")
        self.kitSelect = QtWidgets.QComboBox(self.indoorKitsGroupBox)
        self.kitSelect.setObjectName("kitSelect")
        self.indoorKitsLayout.addWidget(self.kitSelect)
        self.componentList = QtWidgets.QListWidget(self.indoorKitsGroupBox)
        self.componentList.setMinimumHeight(100)
        self.componentList.setObjectName("componentList")
        self.indoorKitsLayout.addWidget(self.componentList)
        self.layoutTabLayout.addWidget(self.indoorKitsGroupBox)
        self.indoorModulesGroupBox = QtWidgets.QGroupBox(self.layoutTab)
        self.indoorModulesGroupBox.setObjectName("indoorModulesGroupBox")
        self.indoorModulesLayout = QtWidgets.QVBoxLayout(self.indoorModulesGroupBox)
        self.indoorModulesLayout.setSpacing(4)
        self.indoorModulesLayout.setObjectName("indoorModulesLayout")
        self.moduleKitSelect = QtWidgets.QComboBox(self.indoorModulesGroupBox)
        self.moduleKitSelect.setObjectName("moduleKitSelect")
        self.indoorModulesLayout.addWidget(self.moduleKitSelect)
        self.moduleComponentList = QtWidgets.QListWidget(self.indoorModulesGroupBox)
        self.moduleComponentList.setMinimumHeight(100)
        self.moduleComponentList.setObjectName("moduleComponentList")
        self.indoorModulesLayout.addWidget(self.moduleComponentList)
        self.layoutTabLayout.addWidget(self.indoorModulesGroupBox)
        self.indoorOptionsBox = QtWidgets.QGroupBox(self.layoutTab)
        self.indoorOptionsBox.setObjectName("indoorOptionsBox")
        self.indoorOptionsLayout = QtWidgets.QVBoxLayout(self.indoorOptionsBox)
        self.indoorOptionsLayout.setObjectName("indoorOptionsLayout")
        self.snapToGridCheck = QtWidgets.QCheckBox(self.indoorOptionsBox)
        self.snapToGridCheck.setObjectName("snapToGridCheck")
        self.indoorOptionsLayout.addWidget(self.snapToGridCheck)
        self.snapToHooksCheck = QtWidgets.QCheckBox(self.indoorOptionsBox)
        self.snapToHooksCheck.setChecked(True)
        self.snapToHooksCheck.setObjectName("snapToHooksCheck")
        self.indoorOptionsLayout.addWidget(self.snapToHooksCheck)
        self.showGridCheck = QtWidgets.QCheckBox(self.indoorOptionsBox)
        self.showGridCheck.setObjectName("showGridCheck")
        self.indoorOptionsLayout.addWidget(self.showGridCheck)
        self.showHooksCheck = QtWidgets.QCheckBox(self.indoorOptionsBox)
        self.showHooksCheck.setChecked(True)
        self.showHooksCheck.setObjectName("showHooksCheck")
        self.indoorOptionsLayout.addWidget(self.showHooksCheck)
        self.gridSizeLayout = QtWidgets.QHBoxLayout()
        self.gridSizeLayout.setObjectName("gridSizeLayout")
        self.gridSizeLabel = QtWidgets.QLabel(self.indoorOptionsBox)
        self.gridSizeLabel.setObjectName("gridSizeLabel")
        self.gridSizeLayout.addWidget(self.gridSizeLabel)
        self.gridSizeSpin = QtWidgets.QDoubleSpinBox(self.indoorOptionsBox)
        self.gridSizeSpin.setMinimum(0.5)
        self.gridSizeSpin.setMaximum(10.0)
        self.gridSizeSpin.setSingleStep(0.5)
        self.gridSizeSpin.setProperty("value", 1.0)
        self.gridSizeSpin.setObjectName("gridSizeSpin")
        self.gridSizeLayout.addWidget(self.gridSizeSpin)
        self.indoorOptionsLayout.addLayout(self.gridSizeLayout)
        self.rotSnapLayout = QtWidgets.QHBoxLayout()
        self.rotSnapLayout.setObjectName("rotSnapLayout")
        self.rotSnapLabel = QtWidgets.QLabel(self.indoorOptionsBox)
        self.rotSnapLabel.setObjectName("rotSnapLabel")
        self.rotSnapLayout.addWidget(self.rotSnapLabel)
        self.rotSnapSpin = QtWidgets.QSpinBox(self.indoorOptionsBox)
        self.rotSnapSpin.setMinimum(1)
        self.rotSnapSpin.setMaximum(90)
        self.rotSnapSpin.setProperty("value", 15)
        self.rotSnapSpin.setObjectName("rotSnapSpin")
        self.rotSnapLayout.addWidget(self.rotSnapSpin)
        self.indoorOptionsLayout.addLayout(self.rotSnapLayout)
        self.layoutTabLayout.addWidget(self.indoorOptionsBox)
        self.buildIndoorButton = QtWidgets.QPushButton(self.layoutTab)
        self.buildIndoorButton.setObjectName("buildIndoorButton")
        self.layoutTabLayout.addWidget(self.buildIndoorButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutTabLayout.addItem(spacerItem4)
        self.rightPanel.addTab(self.layoutTab, "")
        self.horizontalLayout.addWidget(self.rightPanel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionAddRoom = QtWidgets.QAction(MainWindow)
        self.actionAddRoom.setObjectName("actionAddRoom")
        self.actionAddDoorHook = QtWidgets.QAction(MainWindow)
        self.actionAddDoorHook.setObjectName("actionAddDoorHook")
        self.actionAddTrack = QtWidgets.QAction(MainWindow)
        self.actionAddTrack.setObjectName("actionAddTrack")
        self.actionAddObstacle = QtWidgets.QAction(MainWindow)
        self.actionAddObstacle.setObjectName("actionAddObstacle")
        self.actionImportTexture = QtWidgets.QAction(MainWindow)
        self.actionImportTexture.setObjectName("actionImportTexture")
        self.actionGenerateWalkmesh = QtWidgets.QAction(MainWindow)
        self.actionGenerateWalkmesh.setObjectName("actionGenerateWalkmesh")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHide3DView = QtWidgets.QAction(MainWindow)
        self.actionHide3DView.setObjectName("actionHide3DView")
        self.actionHide2DView = QtWidgets.QAction(MainWindow)
        self.actionHide2DView.setObjectName("actionHide2DView")
        self.lytToolbar.addAction(self.actionAddRoom)
        self.lytToolbar.addAction(self.actionAddDoorHook)
        self.lytToolbar.addAction(self.actionAddTrack)
        self.lytToolbar.addAction(self.actionAddObstacle)
        self.lytToolbar.addSeparator()
        self.lytToolbar.addAction(self.actionImportTexture)
        self.lytToolbar.addAction(self.actionGenerateWalkmesh)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionUndo)
        self.menuFile.addAction(self.actionRedo)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInstructions)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.modeLabelWidget.setText(_translate("MainWindow", "Mode:"))
        self.modeSelector.setToolTip(_translate("MainWindow", "Switch editor mode (Layout builds rooms, Object places GIT\n"
"             instances,\n"
"             Walkmesh edits walk surfaces)"))
        self.modeSelector.setItemText(0, _translate("MainWindow", "Object Mode"))
        self.modeSelector.setItemText(1, _translate("MainWindow", "Layout Mode"))
        self.modeSelector.setItemText(2, _translate("MainWindow", "Walkmesh Mode"))
        self.toolSelectBtn.setText(_translate("MainWindow", "Select (F1)"))
        self.toolSelectBtn.setToolTip(_translate("MainWindow", "Select tool — click to select instances [F1]"))
        self.toolMoveBtn.setText(_translate("MainWindow", "Move (F2)"))
        self.toolMoveBtn.setToolTip(_translate("MainWindow", "Move tool — drag to translate selected instances [F2]"))
        self.toolRotateBtn.setText(_translate("MainWindow", "Rotate (F3)"))
        self.toolRotateBtn.setToolTip(_translate("MainWindow", "Rotate tool — drag to rotate selected instances [F3]"))
        self.snapCheck.setText(_translate("MainWindow", "Snap"))
        self.snapCheck.setToolTip(_translate("MainWindow", "Enable grid snapping for move/place (Object mode)"))
        self.snapSizeSpin.setSuffix(_translate("MainWindow", " m"))
        self.snapSizeSpin.setToolTip(_translate("MainWindow", "Grid snap increment (meters)"))
        self.rotSnapCheck.setText(_translate("MainWindow", "Rot Snap"))
        self.rotSnapCheck.setToolTip(_translate("MainWindow", "Enable rotation snapping (Object mode)"))
        self.rotSnapDegreeSpin.setSuffix(_translate("MainWindow", "°"))
        self.rotSnapDegreeSpin.setToolTip(_translate("MainWindow", "Rotation snap increment (degrees)"))
        self.sceneOptionsLabel.setText(_translate("MainWindow", "Scene"))
        self.lockInstancesCheck.setToolTip(_translate("MainWindow", "Lock all instances in place"))
        self.cursorCheck.setToolTip(_translate("MainWindow", "Display cursor at mouse"))
        self.roomBoundariesCheck.setToolTip(_translate("MainWindow", "Show room boundary boxes and room labels in 2D view"))
        self.roomBoundariesCheck.setText(_translate("MainWindow", "Rooms"))
        self.flatGridCheck.setToolTip(_translate("MainWindow", "Show world-space grid in 2D view"))
        self.flatGridCheck.setText(_translate("MainWindow", "Grid"))
        self.walkmeshEdgesCheck.setToolTip(_translate("MainWindow", "Show walkmesh edges in 2D view (Object/Walkmesh modes)"))
        self.walkmeshEdgesCheck.setText(_translate("MainWindow", "Walkmesh edges"))
        self.renderOptionsLabel.setText(_translate("MainWindow", "Render"))
        self.backfaceCheck.setToolTip(_translate("MainWindow", "Enable backface culling"))
        self.lightmapCheck.setToolTip(_translate("MainWindow", "Enable lightmaps"))
        self.visibilityFiltersLabel.setText(_translate("MainWindow", "Visible Types"))
        self.viewCreatureCheck.setToolTip(_translate("MainWindow", "Creatures"))
        self.viewDoorCheck.setToolTip(_translate("MainWindow", "Doors"))
        self.viewPlaceableCheck.setToolTip(_translate("MainWindow", "Placeables"))
        self.viewStoreCheck.setToolTip(_translate("MainWindow", "Merchants"))
        self.viewSoundCheck.setToolTip(_translate("MainWindow", "Sounds"))
        self.viewWaypointCheck.setToolTip(_translate("MainWindow", "Waypoints"))
        self.viewCameraCheck.setToolTip(_translate("MainWindow", "Cameras"))
        self.viewEncounterCheck.setToolTip(_translate("MainWindow", "Encounters"))
        self.viewTriggerCheck.setToolTip(_translate("MainWindow", "Triggers"))
        self.pickHiddenCheck.setToolTip(_translate("MainWindow", "Allow selecting instances that are hidden by type (e.g.\n"
"                creatures when Creatures is unchecked)"))
        self.pickHiddenCheck.setText(_translate("MainWindow", "Pick hidden"))
        self.resourceSearchEdit.setPlaceholderText(_translate("MainWindow", "Search resources..."))
        self.leftPanel.setTabText(self.leftPanel.indexOf(self.resourceTab), _translate("MainWindow", "Resources"))
        self.lytTree.headerItem().setText(0, _translate("MainWindow", "Layout Elements"))
        self.modelLabel.setText(_translate("MainWindow", "Model:"))
        self.browseModelButton.setText(_translate("MainWindow", "..."))
        self.positionLabel.setText(_translate("MainWindow", "Position:"))
        self.rotationLabel.setText(_translate("MainWindow", "Rotation:"))
        self.lytElementTabs.setTabText(self.lytElementTabs.indexOf(self.roomTab), _translate("MainWindow", "Room"))
        self.roomNameLabel.setText(_translate("MainWindow", "Room:"))
        self.doorNameLabel.setText(_translate("MainWindow", "Door:"))
        self.lytElementTabs.setTabText(self.lytElementTabs.indexOf(self.doorHookTab), _translate("MainWindow", "Door Hook"))
        self.leftPanel.setTabText(self.leftPanel.indexOf(self.lytTab), _translate("MainWindow", "Layout"))
        self.walkmeshPainterBox.setTitle(_translate("MainWindow", "Walkmesh Painter"))
        self.enablePaintCheck.setText(_translate("MainWindow", "Enable Painting (P)"))
        self.colorizeMaterialsCheck.setText(_translate("MainWindow", "Colorize Materials"))
        self.resetPaintButton.setText(_translate("MainWindow", "Reset Selected"))
        self.walkmeshFacePropsBox.setTitle(_translate("MainWindow", "Selected Face"))
        self.faceMaterialLabel.setText(_translate("MainWindow", "Material:"))
        self.faceWalkLabel.setText(_translate("MainWindow", "Walkable:"))
        self.faceWalkCheckLabel.setText(_translate("MainWindow", "Walk Check:"))
        self.faceLosLabel.setText(_translate("MainWindow", "Line of Sight:"))
        self.leftPanel.setTabText(self.leftPanel.indexOf(self.walkmeshTab), _translate("MainWindow", "Walkmesh"))
        self.visInfoLabel.setText(_translate("MainWindow", "Room-to-room visibility matrix. Check rooms that should be visible\n"
"              from each other."))
        self.visMatrix.headerItem().setText(0, _translate("MainWindow", "Room"))
        self.visSetAllButton.setText(_translate("MainWindow", "Set All Visible"))
        self.visClearAllButton.setText(_translate("MainWindow", "Clear All"))
        self.leftPanel.setTabText(self.leftPanel.indexOf(self.visTab), _translate("MainWindow", "VIS"))
        self.instanceSearchEdit.setPlaceholderText(_translate("MainWindow", "Search instances..."))
        self.propertiesGroup.setTitle(_translate("MainWindow", "Selected Instance"))
        self.propResRefLabel.setText(_translate("MainWindow", "ResRef:"))
        self.propResRefValue.setText(_translate("MainWindow", "—"))
        self.propTypeLabel.setText(_translate("MainWindow", "Type:"))
        self.propTypeValue.setText(_translate("MainWindow", "—"))
        self.label.setText(_translate("MainWindow", "X:"))
        self.label1.setText(_translate("MainWindow", "Y:"))
        self.label2.setText(_translate("MainWindow", "Z:"))
        self.label3.setText(_translate("MainWindow", "Bearing°:"))
        self.propOpenBlueprintBtn.setText(_translate("MainWindow", "Open Blueprint..."))
        self.rightPanel.setTabText(self.rightPanel.indexOf(self.instancesTab), _translate("MainWindow", "Instances"))
        self.indoorPreviewBox.setTitle(_translate("MainWindow", "Preview"))
        self.indoorKitsGroupBox.setTitle(_translate("MainWindow", "Kits"))
        self.indoorModulesGroupBox.setTitle(_translate("MainWindow", "Modules"))
        self.indoorOptionsBox.setTitle(_translate("MainWindow", "Options"))
        self.snapToGridCheck.setText(_translate("MainWindow", "Snap to Grid (G)"))
        self.snapToHooksCheck.setText(_translate("MainWindow", "Snap to Hooks (H)"))
        self.showGridCheck.setText(_translate("MainWindow", "Show Grid"))
        self.showHooksCheck.setText(_translate("MainWindow", "Show Hooks"))
        self.gridSizeLabel.setText(_translate("MainWindow", "Grid Size:"))
        self.rotSnapLabel.setText(_translate("MainWindow", "Rotation Snap:"))
        self.rotSnapSpin.setSuffix(_translate("MainWindow", "°"))
        self.buildIndoorButton.setText(_translate("MainWindow", "Build Module (.mod)"))
        self.buildIndoorButton.setToolTip(_translate("MainWindow", "Compile the indoor layout into a playable .mod file"))
        self.rightPanel.setTabText(self.rightPanel.indexOf(self.layoutTab), _translate("MainWindow", "Indoor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Save GIT"))
        self.actionAddRoom.setText(_translate("MainWindow", "Add Room"))
        self.actionAddRoom.setToolTip(_translate("MainWindow", "Add a new room to the layout"))
        self.actionAddDoorHook.setText(_translate("MainWindow", "Add Door Hook"))
        self.actionAddDoorHook.setToolTip(_translate("MainWindow", "Add a new door hook"))
        self.actionAddTrack.setText(_translate("MainWindow", "Add Track"))
        self.actionAddTrack.setToolTip(_translate("MainWindow", "Add a new track element"))
        self.actionAddObstacle.setText(_translate("MainWindow", "Add Obstacle"))
        self.actionAddObstacle.setToolTip(_translate("MainWindow", "Add a new obstacle"))
        self.actionImportTexture.setText(_translate("MainWindow", "Import Texture"))
        self.actionImportTexture.setToolTip(_translate("MainWindow", "Import a custom texture"))
        self.actionGenerateWalkmesh.setText(_translate("MainWindow", "Generate Walkmesh"))
        self.actionGenerateWalkmesh.setToolTip(_translate("MainWindow", "Generate walkmesh from room layout"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+F4"))
        self.actionHide3DView.setText(_translate("MainWindow", "Hide 3D View"))
        self.actionHide2DView.setText(_translate("MainWindow", "Hide 2D View"))
from toolset.gui.widgets.renderer.module import ModuleRenderer
from toolset.gui.widgets.renderer.walkmesh import WalkmeshRenderer
from toolset.gui.windows.indoor_builder.renderer import IndoorMapRenderer
import resources_rc
