# Form implementation generated from reading ui file '..\ui\windows\file_selection.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.detailedCheckbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.detailedCheckbox.setObjectName("detailedCheckbox")
        self.mainLayout.addWidget(self.detailedCheckbox)
        self.resourceTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resourceTable.sizePolicy().hasHeightForWidth())
        self.resourceTable.setSizePolicy(sizePolicy)
        self.resourceTable.setWordWrap(True)
        self.resourceTable.setObjectName("resourceTable")
        self.resourceTable.setColumnCount(4)
        self.resourceTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resourceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resourceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resourceTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resourceTable.setHorizontalHeaderItem(3, item)
        self.mainLayout.addWidget(self.resourceTable)
        self.openButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openButton.setObjectName("openButton")
        self.mainLayout.addWidget(self.openButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Selection"))
        self.detailedCheckbox.setText(_translate("MainWindow", "Show detailed"))
        item = self.resourceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.resourceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Path"))
        item = self.resourceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Offset"))
        item = self.resourceTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Size"))
        self.openButton.setText(_translate("MainWindow", "Open"))
