# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\breadcrumbs_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(400, 30)
        Widget.setStyleSheet("QWidget {\n"
"    background-color: palette(window);\n"
"    }\n"
"    QPushButton {\n"
"    background-color: transparent;\n"
"    color: palette(windowText);\n"
"    border: none;\n"
"    padding: 2px 4px;\n"
"    text-align: left;\n"
"    }\n"
"    QPushButton:hover {\n"
"    background-color: palette(button);\n"
"    }\n"
"    QLabel {\n"
"    color: palette(mid);\n"
"    }")
        self.mainLayout = QtWidgets.QHBoxLayout(Widget)
        self.mainLayout.setContentsMargins(4, 2, 4, 2)
        self.mainLayout.setSpacing(2)
        self.mainLayout.setObjectName("mainLayout")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        pass
