# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\media_player_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_MediaPlayerWidget(object):
    def setupUi(self, MediaPlayerWidget):
        MediaPlayerWidget.setObjectName("MediaPlayerWidget")
        MediaPlayerWidget.resize(600, 40)
        MediaPlayerWidget.setMinimumSize(QtCore.QSize(0, 40))
        self.mainLayout = QtWidgets.QVBoxLayout(MediaPlayerWidget)
        self.mainLayout.setContentsMargins(4, 4, 4, 4)
        self.mainLayout.setSpacing(4)
        self.mainLayout.setObjectName("mainLayout")
        self.controlsLayout = QtWidgets.QHBoxLayout()
        self.controlsLayout.setContentsMargins(0, 0, 0, 0)
        self.controlsLayout.setSpacing(4)
        self.controlsLayout.setObjectName("controlsLayout")
        self.playPauseButton = QtWidgets.QPushButton(MediaPlayerWidget)
        self.playPauseButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playPauseButton.setMinimumSize(QtCore.QSize(32, 32))
        self.playPauseButton.setMaximumSize(QtCore.QSize(32, 32))
        self.playPauseButton.setObjectName("playPauseButton")
        self.controlsLayout.addWidget(self.playPauseButton)
        self.stopButton = QtWidgets.QPushButton(MediaPlayerWidget)
        self.stopButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stopButton.setMinimumSize(QtCore.QSize(32, 32))
        self.stopButton.setMaximumSize(QtCore.QSize(32, 32))
        self.stopButton.setObjectName("stopButton")
        self.controlsLayout.addWidget(self.stopButton)
        self.timeSlider = QtWidgets.QSlider(MediaPlayerWidget)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeSlider.setMouseTracking(True)
        self.timeSlider.setMinimum(0)
        self.timeSlider.setMaximum(0)
        self.timeSlider.setSingleStep(1000)
        self.timeSlider.setPageStep(10000)
        self.timeSlider.setObjectName("timeSlider")
        self.controlsLayout.addWidget(self.timeSlider)
        self.timeLabel = QtWidgets.QLabel(MediaPlayerWidget)
        self.timeLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.controlsLayout.addWidget(self.timeLabel)
        self.volumeContainer = QtWidgets.QWidget(MediaPlayerWidget)
        self.volumeContainer.setObjectName("volumeContainer")
        self.volumeLayout = QtWidgets.QHBoxLayout(self.volumeContainer)
        self.volumeLayout.setContentsMargins(0, 0, 0, 0)
        self.volumeLayout.setSpacing(4)
        self.volumeLayout.setObjectName("volumeLayout")
        self.muteButton = QtWidgets.QPushButton(self.volumeContainer)
        self.muteButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.muteButton.setMinimumSize(QtCore.QSize(28, 28))
        self.muteButton.setMaximumSize(QtCore.QSize(28, 28))
        self.muteButton.setObjectName("muteButton")
        self.volumeLayout.addWidget(self.muteButton)
        self.volumeSlider = QtWidgets.QSlider(self.volumeContainer)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.volumeSlider.setMinimumSize(QtCore.QSize(80, 0))
        self.volumeSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.volumeSlider.setMinimum(0)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 75)
        self.volumeSlider.setObjectName("volumeSlider")
        self.volumeLayout.addWidget(self.volumeSlider)
        self.controlsLayout.addWidget(self.volumeContainer)
        self.speedButton = QtWidgets.QToolButton(MediaPlayerWidget)
        self.speedButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.speedButton.setMinimumSize(QtCore.QSize(50, 28))
        self.speedButton.setMaximumSize(QtCore.QSize(50, 28))
        self.speedButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.speedButton.setObjectName("speedButton")
        self.controlsLayout.addWidget(self.speedButton)
        self.mainLayout.addLayout(self.controlsLayout)

        self.retranslateUi(MediaPlayerWidget)
        QtCore.QMetaObject.connectSlotsByName(MediaPlayerWidget)

    def retranslateUi(self, MediaPlayerWidget):
        _translate = QtCore.QCoreApplication.translate
        self.playPauseButton.setToolTip(_translate("MediaPlayerWidget", "Play/Pause (Space)"))
        self.stopButton.setToolTip(_translate("MediaPlayerWidget", "Stop (S)"))
        self.timeSlider.setToolTip(_translate("MediaPlayerWidget", "Drag to seek, click to jump (Left/Right: ±5s, Shift+Left/Right: ±1s)"))
        self.timeLabel.setToolTip(_translate("MediaPlayerWidget", "Current time / Total duration"))
        self.timeLabel.setText(_translate("MediaPlayerWidget", "00:00 / 00:00"))
        self.muteButton.setToolTip(_translate("MediaPlayerWidget", "Mute/Unmute (M)"))
        self.speedButton.setToolTip(_translate("MediaPlayerWidget", "Playback Speed (Click to cycle, [ to slow, ] to fast)"))
        self.speedButton.setText(_translate("MediaPlayerWidget", "1.0x"))
