# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui\widgets\pth_status_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 30)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLabel = QtWidgets.QLabel(Form)
        self.leftLabel.setObjectName("leftLabel")
        self.horizontalLayout.addWidget(self.leftLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.centerLabel = QtWidgets.QLabel(Form)
        self.centerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.centerLabel.setObjectName("centerLabel")
        self.horizontalLayout.addWidget(self.centerLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.rightLabel = QtWidgets.QLabel(Form)
        self.rightLabel.setObjectName("rightLabel")
        self.horizontalLayout.addWidget(self.rightLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.leftLabel.setText(_translate("Form", "Left Status"))
        self.centerLabel.setText(_translate("Form", "Center Status"))
        self.rightLabel.setText(_translate("Form", "Right Status"))
